'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CLIENTESN
    Public Property Codigo_clie As String
    Public Property Nombre_clie As String
    Public Property identidad As String
    Public Property tributario As String
    Public Property cl_fecha As Nullable(Of Date)
    Public Property CL_STATUS As String
    Public Property CL_COMPANIA As String
    Public Property Dir_cliente As String
    Public Property Dir2_client As String
    Public Property Dir3_client As String
    Public Property Dir4_client As String
    Public Property Dir5_client As String
    Public Property Telef_clien As String
    Public Property CL_CELULAR As String
    Public Property CL_EMAIL As String
    Public Property cl_conyunom As String
    Public Property cl_conyutel As String
    Public Property cl_conyudir As String
    Public Property CL_PARENt As String
    Public Property Cod_zona As String
    Public Property CL_VENDEDOR As String
    Public Property cl_usuario As String
    Public Property cl_terminal As String
    Public Property longitud As Nullable(Of Decimal)
    Public Property latitud As Nullable(Of Decimal)
    Public Property secuencia As Nullable(Of Integer)
    Public Property diavisita As Nullable(Of Short)
    Public Property semana As Nullable(Of Short)
    Public Property cierre As String
    Public Property tempo As String
    Public Property departa As String
    Public Property municipio As String
    Public Property circuito As String
    Public Property liquida As String
    Public Property hora As String
    Public Property FechaDoc As String

End Class
