'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DataClient

    '''<summary>
    '''txtidentiCliapp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidentiCliapp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxCelular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCelular As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPrimaApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPrimaApp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dlDeptoCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlDeptoCliente As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dlCiudadCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlCiudadCliente As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtdir1Cliapp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdir1Cliapp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAddress2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAddress3 As Global.System.Web.UI.WebControls.TextBox
End Class
