'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CONTRATO
    Public Property CONT_NUMERO As String
    Public Property CONT_FECHA As Nullable(Of Date)
    Public Property Codigo_clie As String
    Public Property CONT_DESCRI As String
    Public Property CONT_DESC2 As String
    Public Property CONT_DESC3 As String
    Public Property CONT_VALOR As Nullable(Of Decimal)
    Public Property CONT_CREDIT As String
    Public Property CONT_PRIMA As Nullable(Of Decimal)
    Public Property CONT_NUMCUO As Nullable(Of Short)
    Public Property CONT_VALCUO As Nullable(Of Decimal)
    Public Property CONT_BENEFI As String
    Public Property CONT_BENFEC As Nullable(Of Date)
    Public Property CONT_BENPAR As String
    Public Property CONT_CLIENT As String
    Public Property CONT_SUPERV As String
    Public Property CONT_FSUPER As Nullable(Of Date)
    Public Property cont_vended As String
    Public Property cont_cobrad As String
    Public Property CONT_SALDO As Nullable(Of Decimal)
    Public Property CONT_FECAM As Nullable(Of Date)
    Public Property CONT_CJARD As String
    Public Property CONT_CLETRA As String
    Public Property CONT_CNUM As String
    Public Property CONT_SERVI As String
    Public Property CONT_CANTI As Nullable(Of Short)
    Public Property CONT_FOTO As Byte()
    Public Property CONT_COMPA As String
    Public Property CONT_CANT2 As Nullable(Of Short)
    Public Property CONT_SERV2 As String
    Public Property CONT_CANT3 As Nullable(Of Short)
    Public Property CONT_SERV3 As String
    Public Property CONT_FOT2 As Byte()
    Public Property CONT_FOT3 As Byte()
    Public Property CONT_FOT4 As Byte()
    Public Property CONT_FOT5 As Byte()
    Public Property CONT_FOT6 As Byte()
    Public Property CONT_CJAR2 As String
    Public Property CONT_CJAR3 As String
    Public Property CONT_CLET2 As String
    Public Property CONT_CLET3 As String
    Public Property CONT_CNU2 As String
    Public Property CONT_CNU3 As String
    Public Property CONT_CSUPER As String
    Public Property CONT_FECPRO As Nullable(Of Date)
    Public Property CONT_SVAL1 As Nullable(Of Decimal)
    Public Property CONT_SVAL2 As Nullable(Of Decimal)
    Public Property CONT_SVAL3 As Nullable(Of Decimal)
    Public Property CONT_RFECHA As Nullable(Of Date)
    Public Property CONT_RHORA As String
    Public Property CONT_FECTER As Nullable(Of Date)
    Public Property CONT_HORTER As String
    Public Property CONT_NOTAS As String
    Public Property SUBIVIEJO As String
    Public Property CONT_SUBIFI As String
    Public Property CONT_LIDER As String

End Class
