'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class View_ACTUACORRELA
    Public Property EMPRESA As String
    Public Property codigo_cobr As String
    Public Property NUMERO As String
    Public Property A As String
    Public Property B As String

End Class
