'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ADIBA2
    Public Property BNumcuenta As String
    Public Property Bcod_tipo As String
    Public Property BNum_doc As String
    Public Property BNumero_cue As String
    Public Property busuario As String
    Public Property bterminal As String
    Public Property bplanilla As String
    Public Property BLEMPIRAS As Nullable(Of Decimal)
    Public Property BFecha_mov As Nullable(Of Date)
    Public Property BDescripcio As String
    Public Property BPor_concep As String
    Public Property bpor_conc2 As String
    Public Property bpor_conc3 As String
    Public Property bopero As String
    Public Property BStatus As String
    Public Property BDebe As Nullable(Of Decimal)
    Public Property BHaber As Nullable(Of Decimal)
    Public Property CCod_partid As String
    Public Property bcambmov As Nullable(Of Decimal)
    Public Property BMOVIBORRAD As String
    Public Property BMOVIFBORRA As Nullable(Of Date)
    Public Property BMOVIMODIFI As String
    Public Property BMOVIFMODIF As Nullable(Of Date)
    Public Property BGENERADO As String
    Public Property BFECHPOST As Nullable(Of Date)
    Public Property BSELECCION As String
    Public Property Btransfcue As String
    Public Property BFECHCONCIL As Nullable(Of Date)
    Public Property BCODIGO As String
    Public Property bhoramov As String
    Public Property bffecha As Nullable(Of Date)
    Public Property bidentidad As String

End Class
