'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AUXPRE
    Public Property AUXPRE_NUM As String
    Public Property AUXPRE_TIPO As String
    Public Property PREST_NUMER As String
    Public Property AUXPRE_PFEC As Nullable(Of Date)
    Public Property AUXPRE_FECH As Nullable(Of Date)
    Public Property AUXPRE_CONC As String
    Public Property AUXPRE_DIVI As String
    Public Property AUXPRE_DEBE As Nullable(Of Decimal)
    Public Property AUXPRE_HABE As Nullable(Of Decimal)
    Public Property AUXPRE_ICAM As Decimal
    Public Property AUXPRE_PART As String
    Public Property auxpre_inte As Decimal
    Public Property prest_moded As String
    Public Property AUXPRE_CAMB As Nullable(Of Decimal)
    Public Property auxpre_ende As String
    Public Property AUXPRE_CUEN As String

End Class
