'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BODEGA
    Public Property CODIGO_BODE As String
    Public Property TIPO_BODEGA As String
    Public Property NOMBRE_BODE As String
    Public Property Codigo_sucu As String
    Public Property bod_usuario As String
    Public Property bod_termina As String
    Public Property EA_INVCONT As String
    Public Property EA_DEVCOMP As String
    Public Property EA_MERTRAN As String
    Public Property EA_COSTOV As String
    Public Property EA_CUEINV As String
    Public Property BOD_STATUS As String
    Public Property BOD_COMPA As String
    Public Property BODLETRAS As String
    Public Property BODCORENT As Nullable(Of Integer)
    Public Property BODCSALIDAS As Nullable(Of Integer)
    Public Property BODCENTRADA As Nullable(Of Integer)

End Class
