'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CABSEG
    Public Property SEG_USUARIO As String
    Public Property SEG_PASSWD As String
    Public Property SEG_MENU As String
    Public Property SEG_09 As String
    Public Property SEG_59 As String
    Public Property SEG_90 As String
    Public Property SEG_EXI As String
    Public Property SEG_SUCU As String
    Public Property SEG_COMPA As String
    Public Property SEG_FECHAR As Nullable(Of Date)
    Public Property SEG_TIPOR As String
    Public Property SEG_NOMUSU As String
    Public Property Codigo_sucu As String
    Public Property MantClie As String
    Public Property CambComp As String
    Public Property CancComi As String
    Public Property AgreEntre As String
    Public Property CambiPlan As String
    Public Property ModiEntre As String
    Public Property CambVend As String
    Public Property CambDatos As String
    Public Property AsigCobra As String
    Public Property Vales As String
    Public Property Recibos As String
    Public Property CambUbic As String
    Public Property SEG_FIRMA As Byte()

End Class
