'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CLICOB
    Public Property Codigo_clie As String
    Public Property clicob_fech As Date
    Public Property codigo_cobr As String
    Public Property clicob_usua As String

End Class
