'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COBRADOR
    Public Property codigo_cobr As String
    Public Property nombre_cobr As String
    Public Property COBR_STATUS As String
    Public Property cob_telefo As String
    Public Property cob_zona As String
    Public Property cob_fingre As Nullable(Of Date)
    Public Property cob_lider As String
    Public Property COB_DIRECCI As String
    Public Property COB_FECHING As Nullable(Of Date)
    Public Property COB_SUPERVI As String
    Public Property COB_EMAIL As String
    Public Property COB_TELTRAB As String
    Public Property COB_IDENTID As String
    Public Property COB_FECNAC As Nullable(Of Date)
    Public Property COB_FOTO As Byte()
    Public Property COB_SUCU As String

End Class
