'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPARTIDA
    Public Property CCod_partid As String
    Public Property cterminal As String
    Public Property cusuario As String
    Public Property conta_ctipo As String
    Public Property COD_NATURA As String
    Public Property CFecha As Nullable(Of Date)
    Public Property RESUMEN As String
    Public Property ccodtipo As String
    Public Property CDescrip_pa As String
    Public Property CDESCRIP2 As String
    Public Property cdescri2 As String
    Public Property cdescri3 As String
    Public Property CULTIMA As Nullable(Of Short)
    Public Property CCFECHA As Nullable(Of Date)
    Public Property cconciliado As String
    Public Property conta_compa As String
    Public Property cpartiborra As String
    Public Property cpartifborr As Nullable(Of Date)
    Public Property cpartimodif As String
    Public Property cpartifmodi As Nullable(Of Date)

End Class
