'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DETMOV
    Public Property Numero_docu As String
    Public Property Eys As String
    Public Property Tipodoc As String
    Public Property detmoitem As Short
    Public Property producto As String
    Public Property Cod_product As String
    Public Property TIPO_BODEGA As String
    Public Property Icod_tipo As String
    Public Property DEQUIVALE As Nullable(Of Decimal)
    Public Property DCANTIDAD As Nullable(Of Decimal)
    Public Property DPRECIO As Nullable(Of Decimal)
    Public Property DMULTIPLI As Nullable(Of Decimal)
    Public Property DMANOBRA As Nullable(Of Decimal)
    Public Property DETPRECIO As Nullable(Of Decimal)
    Public Property DSUBTOTAL As Nullable(Of Decimal)
    Public Property costo_u As Nullable(Of Decimal)
    Public Property DGASTOSIN As Nullable(Of Decimal)
    Public Property DESCRI2 As String
    Public Property DESC2_FAC As Nullable(Of Short)
    Public Property DESC3_FAC As Nullable(Of Short)
    Public Property marque As String
    Public Property dtarjet As Nullable(Of Decimal)
    Public Property DLINEA As String
    Public Property dnumef As String
    Public Property CNUEVOCODI As String
    Public Property DGSUBTOTAL As Nullable(Of Decimal)
    Public Property para_bodega As String
    Public Property lib1 As Nullable(Of Short)
    Public Property DETBODEGA As String
    Public Property CODIGO_BODE As String
    Public Property IDESCRIPCIO As String
    Public Property Cantidad As Nullable(Of Decimal)
    Public Property CARGAR As String
    Public Property dfecha As Nullable(Of Date)
    Public Property Desc_fact As Nullable(Of Decimal)
    Public Property Precio_unit As Nullable(Of Decimal)
    Public Property IMP As Nullable(Of Decimal)
    Public Property SUB_IMP As Nullable(Of Decimal)
    Public Property comis_ve As Nullable(Of Decimal)
    Public Property sub_libera As Nullable(Of Decimal)
    Public Property DCLIENTE As String

End Class
