'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DETPAGAR
    Public Property Nump_doc As String
    Public Property Tdocp As String
    Public Property Numero_docu As String
    Public Property Eys As String
    Public Property Tipodoc As String
    Public Property Rcantp As Nullable(Of Decimal)
    Public Property RCANTC As Nullable(Of Decimal)
    Public Property DETPAFECHA As Nullable(Of Date)

End Class
