'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EXIBOD
    Public Property Cod_product As String
    Public Property CODIGO_BODE As String
    Public Property TIPO_BODEGA As String
    Public Property Icod_tipo As String
    Public Property enuevocodi As String
    Public Property EXI_DATE As Nullable(Of Date)
    Public Property EXI_BOD As Nullable(Of Decimal)
    Public Property exi_fina As Nullable(Of Decimal)
    Public Property reserva As Nullable(Of Decimal)
    Public Property exist_cierr As Nullable(Of Decimal)
    Public Property exisf_cierr As Nullable(Of Decimal)
    Public Property fecha_cierr As Nullable(Of Date)
    Public Property EXI_CAPTURA As Nullable(Of Decimal)
    Public Property EXI_CONGELA As Nullable(Of Decimal)
    Public Property EXI_FECHA As Nullable(Of Date)
    Public Property exi_fecong As Nullable(Of Date)
    Public Property exi_horcap As String
    Public Property EXI_DIGITO As String

End Class
