'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LISTP21
    Public Property cod_listpre As String
    Public Property Cod_product As String
    Public Property pluref As String
    Public Property stockcode As String
    Public Property lpreciodol As Nullable(Of Decimal)

End Class
