'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NRECIBO
    Public Property NNUM_DOC As String
    Public Property NTDOC As String
    Public Property NRTIPODOC As String
    Public Property NCOBRADO_EN As String
    Public Property NRCONCEPTO As String
    Public Property NRCAMBIO As Decimal
    Public Property NRSUCURSAL As String
    Public Property NCODIGO_COB As String
    Public Property NFECHA_RECI As Date
    Public Property NRFECHA As Date
    Public Property NPOR_LEMPIR As Decimal
    Public Property NRTIPODEBI As String
    Public Property NCODCLIENTE As String
    Public Property NRHORA As String
    Public Property NRTERMINO As String
    Public Property NRCODIGOCLI As String
    Public Property NCXC_CTIPO As String
    Public Property NRUSUARIO As String
    Public Property NRNOMBRECLI As String
    Public Property NRCONCILIAD As String
    Public Property NRCODVEND As String

End Class
