'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLASUC
    Public Property P_cod_sucur As String
    Public Property P_nomb_sucu As String
    Public Property P_ENSUC As String
    Public Property cod_compani As String
    Public Property P_ihss As Nullable(Of Decimal)
    Public Property p_apihss As Nullable(Of Decimal)
    Public Property P_tope_ihss As Nullable(Of Decimal)
    Public Property p_ctaihss As String
    Public Property P_CTACOMIS As String
    Public Property P_SALMINI As Nullable(Of Decimal)
    Public Property p_sucpago As Nullable(Of Decimal)
    Public Property p_succomis As Nullable(Of Decimal)
    Public Property p_sucfactor As Nullable(Of Decimal)
    Public Property p_ctafosovi As String
    Public Property p_ctaapihss As String
    Public Property p_ctaapfoso As String
    Public Property p_ctainfop As String
    Public Property p_ctanomina As String
    Public Property p_ctappa13a As String
    Public Property p_ctappa14a As String
    Public Property p_ctappapre As String
    Public Property p_ctaisr As String
    Public Property P_ctapasivo As String
    Public Property P_SMINIMO As Nullable(Of Decimal)
    Public Property P_CTAINCAPA As String

End Class
