'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class POPERA
    Public Property P_cod_opera As String
    Public Property P_nom_opera As String
    Public Property p_tip_opera As String
    Public Property p_ctacontab As String
    Public Property p_asociacio As String
    Public Property P_AFECTAIHS As String
    Public Property P_AFECTAFOS As String
    Public Property P_COOPERATI As String
    Public Property p_opbase As String
    Public Property P_OPSOLOSUC As String

End Class
