'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRESTAMO
    Public Property PREST_NUMER As String
    Public Property PREST_TIPO As String
    Public Property PREST_BANCO As String
    Public Property PREST_BDESC As String
    Public Property PREST_CUENT As String
    Public Property PREST_CUINT As String
    Public Property PREST_GAR1 As String
    Public Property PREST_GAR2 As String
    Public Property PREST_VENCE As Nullable(Of Date)
    Public Property PREST_MONED As String
    Public Property PREST_FACTU As String
    Public Property prest_fechi As Nullable(Of Date)
    Public Property PREST_SALDO As Nullable(Of Decimal)
    Public Property PREST_CAMBI As Nullable(Of Decimal)
    Public Property PREST_INTER As Nullable(Of Decimal)
    Public Property PREST_COMPA As String

End Class
