'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRESTAM1
    Public Property PREST_NUMER As String
    Public Property PREST_ITEM As Short
    Public Property PREST_DEFEC As Nullable(Of Date)
    Public Property PREST_HAFEC As Nullable(Of Date)
    Public Property prest_int As Nullable(Of Decimal)

End Class
