'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SERVICIO
    Public Property serv_tipo As String
    Public Property serv_codigo As String
    Public Property serv_descri As String
    Public Property serv_cant As Nullable(Of Short)
    Public Property serv_valor As Nullable(Of Decimal)
    Public Property serv_codinv As String
    Public Property serv_cuecon As String
    Public Property serv_cuota As Nullable(Of Decimal)
    Public Property serv_maximo As Nullable(Of Decimal)
    Public Property serv_minimo As Nullable(Of Decimal)
    Public Property serv_precio As Nullable(Of Decimal)
    Public Property servin_cod As String
    Public Property serv_empre As String
    Public Property SERV_PMAX As Nullable(Of Decimal)
    Public Property SERV_PMINI As Nullable(Of Decimal)
    Public Property servin_movc As String
    Public Property serv_status As String
    Public Property serv_comnue As Nullable(Of Decimal)
    Public Property serv_valnue As Nullable(Of Decimal)
    Public Property serv_comn2 As Nullable(Of Decimal)

End Class
