'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VALE
    Public Property VAL_EMPRESA As String
    Public Property VAL_NUMERO As Integer
    Public Property VAL_FECHA As Nullable(Of Date)
    Public Property VAL_VALOR As Nullable(Of Decimal)
    Public Property codigo_cobr As String
    Public Property VAL_CONCEPT As String
    Public Property VAL_CONCE2 As String
    Public Property VAL_USUARIO As String
    Public Property VAL_ANULO As String
    Public Property VAL_SUCURS As String
    Public Property VAL_NOMBRE As String
    Public Property VAL_COMPA As String
    Public Property VAL_TIPO As Nullable(Of Short)
    Public Property VAL_ANUHORA As String
    Public Property VAL_ANUTERM As String
    Public Property VAL_ANUFECH As Nullable(Of Date)

End Class
