'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class A_MAESTR
    Public Property A_codigo As String
    Public Property cod_compani As String
    Public Property A_cod_zona As String
    Public Property a_marca As String
    Public Property A_Factura As String
    Public Property A_serie As String
    Public Property A_proveedor As String
    Public Property A_UBICA As String
    Public Property A_COD_DEPA As String
    Public Property A_UBICAINI As String
    Public Property A_RESPOINI As String
    Public Property A_responsab As String
    Public Property A_valor_adq As Nullable(Of Decimal)
    Public Property A_valor_res As Nullable(Of Decimal)
    Public Property A_vida_util As Nullable(Of Decimal)
    Public Property A_fecha_adq As Nullable(Of Date)
    Public Property A_dep_diari As Nullable(Of Decimal)
    Public Property A_dep_mensu As Nullable(Of Decimal)
    Public Property A_dep_anual As Nullable(Of Decimal)
    Public Property A_sucursal As String
    Public Property A_dep_acumu As Nullable(Of Decimal)
    Public Property A_valor_lib As Nullable(Of Decimal)
    Public Property A_partida As String
    Public Property A_ctacont As String
    Public Property A_nombre As String
    Public Property A_status As String
    Public Property A_fecha_ret As Nullable(Of Date)
    Public Property A_motivo As String
    Public Property A_val_retir As Nullable(Of Decimal)
    Public Property A_doc_retir As String
    Public Property a_blob As Byte()

End Class
