'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class AECobrosEntities2
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AECobrosEntities2")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CLIENTESOLDs() As DbSet(Of CLIENTESOLD)
    Public Overridable Property CONTRATO1() As DbSet(Of CONTRATO1)
    'Public Overridable Property Series() As DbSet(Of Serie)
    Public Overridable Property AE_CZONA() As DbSet(Of AE_CZONA)
    Public Overridable Property Almacens() As DbSet(Of Almacen)
    Public Overridable Property Articuloes() As DbSet(Of Articulo)
    Public Overridable Property EstadisticaVisitasDetalles() As DbSet(Of EstadisticaVisitasDetalle)
    Public Overridable Property LogProcesados() As DbSet(Of LogProcesado)
    Public Overridable Property MovArticuloes() As DbSet(Of MovArticulo)
    Public Overridable Property Alphabetical_list_of_products() As DbSet(Of Alphabetical_list_of_product)
    Public Overridable Property Category_Sales_for_1997() As DbSet(Of Category_Sales_for_1997)
    Public Overridable Property ClienteContras() As DbSet(Of ClienteContra)
    Public Overridable Property ClienteContra2() As DbSet(Of ClienteContra2)
    'Public Overridable Property CLIENTES() As DbSet(Of CLIENTE)
    Public Overridable Property COBRADORs() As DbSet(Of COBRADOR)
    Public Overridable Property CONTRATOes() As DbSet(Of CONTRATO)
    Public Overridable Property Current_Product_Lists() As DbSet(Of Current_Product_List)
    Public Overridable Property Customer_and_Suppliers_by_Cities() As DbSet(Of Customer_and_Suppliers_by_City)
    Public Overridable Property CZONAs() As DbSet(Of CZONA)
    Public Overridable Property Invoices() As DbSet(Of Invoice)
    Public Overridable Property Order_Details_Extendeds() As DbSet(Of Order_Details_Extended)
    Public Overridable Property Order_Subtotals() As DbSet(Of Order_Subtotal)
    Public Overridable Property Orders_Qries() As DbSet(Of Orders_Qry)
    Public Overridable Property Product_Sales_for_1997() As DbSet(Of Product_Sales_for_1997)
    Public Overridable Property Products_Above_Average_Prices() As DbSet(Of Products_Above_Average_Price)
    Public Overridable Property Products_by_Categories() As DbSet(Of Products_by_Category)
    Public Overridable Property RECIBOSDIAs() As DbSet(Of RECIBOSDIA)
    Public Overridable Property Sales_by_Categories() As DbSet(Of Sales_by_Category)
    Public Overridable Property Sales_Totals_by_Amounts() As DbSet(Of Sales_Totals_by_Amount)
    Public Overridable Property Summary_of_Sales_by_Quarters() As DbSet(Of Summary_of_Sales_by_Quarter)
    Public Overridable Property Summary_of_Sales_by_Years() As DbSet(Of Summary_of_Sales_by_Year)
    Public Overridable Property View_ACTUACORRELA() As DbSet(Of View_ACTUACORRELA)
    Public Overridable Property View_CLIENTENS() As DbSet(Of View_CLIENTENS)
    Public Overridable Property View_Cobradores() As DbSet(Of View_Cobradores)
    Public Overridable Property View_CORRELA() As DbSet(Of View_CORRELA)
    Public Overridable Property View_CZONA() As DbSet(Of View_CZONA)
    Public Overridable Property View_GRID1() As DbSet(Of View_GRID1)
    Public Overridable Property View_GRID11() As DbSet(Of View_GRID11)
    Public Overridable Property View_GRID2() As DbSet(Of View_GRID2)
    Public Overridable Property View_GRID21() As DbSet(Of View_GRID21)
    Public Overridable Property View_GRID3() As DbSet(Of View_GRID3)
    Public Overridable Property View_GRID31() As DbSet(Of View_GRID31)
    Public Overridable Property View_GRID4() As DbSet(Of View_GRID4)
    Public Overridable Property View_GRID41() As DbSet(Of View_GRID41)

    <DbFunction("AECobrosEntities2", "Saldo")>
    Public Overridable Function Saldo(fecha As Nullable(Of Date)) As IQueryable(Of Saldo_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of Saldo_Result)("[AECobrosEntities2].[Saldo](@Fecha)", fechaParameter)
    End Function

    Public Overridable Function ActuaClientes(cOBRADOR As String) As Integer
        Dim cOBRADORParameter As ObjectParameter = If(cOBRADOR IsNot Nothing, New ObjectParameter("COBRADOR", cOBRADOR), New ObjectParameter("COBRADOR", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActuaClientes", cOBRADORParameter)
    End Function

    Public Overridable Function ActuaClientes2(cOBRADOR As String) As Integer
        Dim cOBRADORParameter As ObjectParameter = If(cOBRADOR IsNot Nothing, New ObjectParameter("COBRADOR", cOBRADOR), New ObjectParameter("COBRADOR", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActuaClientes2", cOBRADORParameter)
    End Function

    Public Overridable Function ActuaContrato(cOBRADOR As String) As Integer
        Dim cOBRADORParameter As ObjectParameter = If(cOBRADOR IsNot Nothing, New ObjectParameter("COBRADOR", cOBRADOR), New ObjectParameter("COBRADOR", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActuaContrato", cOBRADORParameter)
    End Function

    Public Overridable Function ACTUALIZA_SUPERVISIONES(cOBRADOR As String) As Integer
        Dim cOBRADORParameter As ObjectParameter = If(cOBRADOR IsNot Nothing, New ObjectParameter("COBRADOR", cOBRADOR), New ObjectParameter("COBRADOR", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ACTUALIZA_SUPERVISIONES", cOBRADORParameter)
    End Function

    Public Overridable Function ANULAR_RECIBOS(nUM_DOC As String, cODIGO_CLIE As String, uSARIO As String, mOTIVO As String) As Integer
        Dim nUM_DOCParameter As ObjectParameter = If(nUM_DOC IsNot Nothing, New ObjectParameter("NUM_DOC", nUM_DOC), New ObjectParameter("NUM_DOC", GetType(String)))

        Dim cODIGO_CLIEParameter As ObjectParameter = If(cODIGO_CLIE IsNot Nothing, New ObjectParameter("CODIGO_CLIE", cODIGO_CLIE), New ObjectParameter("CODIGO_CLIE", GetType(String)))

        Dim uSARIOParameter As ObjectParameter = If(uSARIO IsNot Nothing, New ObjectParameter("USARIO", uSARIO), New ObjectParameter("USARIO", GetType(String)))

        Dim mOTIVOParameter As ObjectParameter = If(mOTIVO IsNot Nothing, New ObjectParameter("MOTIVO", mOTIVO), New ObjectParameter("MOTIVO", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ANULAR_RECIBOS", nUM_DOCParameter, cODIGO_CLIEParameter, uSARIOParameter, mOTIVOParameter)
    End Function

    Public Overridable Function ANULAR_RECIBOS_LIQUIDADOS(nUM_DOC As String, cODIGO_CLIE As String, uSARIO As String, cOMENTARIO As String) As Integer
        Dim nUM_DOCParameter As ObjectParameter = If(nUM_DOC IsNot Nothing, New ObjectParameter("NUM_DOC", nUM_DOC), New ObjectParameter("NUM_DOC", GetType(String)))

        Dim cODIGO_CLIEParameter As ObjectParameter = If(cODIGO_CLIE IsNot Nothing, New ObjectParameter("CODIGO_CLIE", cODIGO_CLIE), New ObjectParameter("CODIGO_CLIE", GetType(String)))

        Dim uSARIOParameter As ObjectParameter = If(uSARIO IsNot Nothing, New ObjectParameter("USARIO", uSARIO), New ObjectParameter("USARIO", GetType(String)))

        Dim cOMENTARIOParameter As ObjectParameter = If(cOMENTARIO IsNot Nothing, New ObjectParameter("COMENTARIO", cOMENTARIO), New ObjectParameter("COMENTARIO", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ANULAR_RECIBOS_LIQUIDADOS", nUM_DOCParameter, cODIGO_CLIEParameter, uSARIOParameter, cOMENTARIOParameter)
    End Function

    Public Overridable Function CLIENTES_NO_ESTABA(f1 As Nullable(Of Date), f2 As Nullable(Of Date), cobrador As String) As Integer
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CLIENTES_NO_ESTABA", f1Parameter, f2Parameter, cobradorParameter)
    End Function

    Public Overridable Function CONTRATOS_OFICIAL() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CONTRATOS_OFICIAL")
    End Function

    Public Overridable Function CORREO_COBRADORES_SIN_LIQUIDAR() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CORREO_COBRADORES_SIN_LIQUIDAR")
    End Function

    Public Overridable Function CORREO_RECIBOS_OFICINA() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CORREO_RECIBOS_OFICINA")
    End Function

    Public Overridable Function CORREO_SERVICIOS_ENTREGADOS() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CORREO_SERVICIOS_ENTREGADOS")
    End Function

    Public Overridable Function CORREO_SUPERVISIONES() As ObjectResult(Of Nullable(Of Date))
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Date))("CORREO_SUPERVISIONES")
    End Function

    Public Overridable Function CorrigeUbicacionCero() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CorrigeUbicacionCero")
    End Function

    Public Overridable Function CR_CLIENTESNOCOBRO_CANTVISITAS(f1 As Nullable(Of Date), f2 As Nullable(Of Date), cobrador As String) As ObjectResult(Of CR_CLIENTESNOCOBRO_CANTVISITAS_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("f1", f1), New ObjectParameter("f1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("f2", f2), New ObjectParameter("f2", GetType(Date)))

        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CR_CLIENTESNOCOBRO_CANTVISITAS_Result)("CR_CLIENTESNOCOBRO_CANTVISITAS", f1Parameter, f2Parameter, cobradorParameter)
    End Function

    Public Overridable Function CR_COBROS() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CR_COBROS")
    End Function

    Public Overridable Function CR_ESTADISTICA_COBROS(f1 As Nullable(Of Date), f2 As Nullable(Of Date)) As Integer
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CR_ESTADISTICA_COBROS", f1Parameter, f2Parameter)
    End Function

    Public Overridable Function CR_ESTADISTICA_COBROS_AGRUPADO(f1 As Nullable(Of Date), f2 As Nullable(Of Date)) As Integer
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CR_ESTADISTICA_COBROS_AGRUPADO", f1Parameter, f2Parameter)
    End Function

    Public Overridable Function CR_PROCESAR(cobrador As String, usuario As String) As ObjectResult(Of CR_PROCESAR_Result)
        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CR_PROCESAR_Result)("CR_PROCESAR", cobradorParameter, usuarioParameter)
    End Function

    Public Overridable Function CR_REIMPRIMIR_PROCESAR(cobrador As String, usuario As String, liquida2 As String) As ObjectResult(Of CR_REIMPRIMIR_PROCESAR_Result)
        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(String)))

        Dim liquida2Parameter As ObjectParameter = If(liquida2 IsNot Nothing, New ObjectParameter("Liquida2", liquida2), New ObjectParameter("Liquida2", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CR_REIMPRIMIR_PROCESAR_Result)("CR_REIMPRIMIR_PROCESAR", cobradorParameter, usuarioParameter, liquida2Parameter)
    End Function

    Public Overridable Function CustOrderHist(customerID As String) As Integer
        Dim customerIDParameter As ObjectParameter = If(customerID IsNot Nothing, New ObjectParameter("CustomerID", customerID), New ObjectParameter("CustomerID", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CustOrderHist", customerIDParameter)
    End Function

    Public Overridable Function CustOrdersDetail(orderID As Nullable(Of Integer)) As Integer
        Dim orderIDParameter As ObjectParameter = If(orderID.HasValue, New ObjectParameter("OrderID", orderID), New ObjectParameter("OrderID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CustOrdersDetail", orderIDParameter)
    End Function

    Public Overridable Function CustOrdersOrders(customerID As String) As Integer
        Dim customerIDParameter As ObjectParameter = If(customerID IsNot Nothing, New ObjectParameter("CustomerID", customerID), New ObjectParameter("CustomerID", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CustOrdersOrders", customerIDParameter)
    End Function

    Public Overridable Function DISTANCIA_VISITAS(f1 As Nullable(Of Date), f2 As Nullable(Of Date)) As Integer
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("DISTANCIA_VISITAS", f1Parameter, f2Parameter)
    End Function

    Public Overridable Function Employee_Sales_by_Country(beginning_Date As Nullable(Of Date), ending_Date As Nullable(Of Date)) As Integer
        Dim beginning_DateParameter As ObjectParameter = If(beginning_Date.HasValue, New ObjectParameter("Beginning_Date", beginning_Date), New ObjectParameter("Beginning_Date", GetType(Date)))

        Dim ending_DateParameter As ObjectParameter = If(ending_Date.HasValue, New ObjectParameter("Ending_Date", ending_Date), New ObjectParameter("Ending_Date", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Employee_Sales_by_Country", beginning_DateParameter, ending_DateParameter)
    End Function

    Public Overridable Function ENVIARECIBOS(codigo_cobr As String, usuario As String) As ObjectResult(Of Nullable(Of Integer))
        Dim codigo_cobrParameter As ObjectParameter = If(codigo_cobr IsNot Nothing, New ObjectParameter("codigo_cobr", codigo_cobr), New ObjectParameter("codigo_cobr", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("ENVIARECIBOS", codigo_cobrParameter, usuarioParameter)
    End Function

    Public Overridable Function ESTADISTICA_COBROS(f1 As Nullable(Of Date), f2 As Nullable(Of Date)) As Integer
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ESTADISTICA_COBROS", f1Parameter, f2Parameter)
    End Function

    Public Overridable Function Get_Clientes(cobrador As String) As ObjectResult(Of Get_Clientes_Result)
        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Get_Clientes_Result)("Get_Clientes", cobradorParameter)
    End Function

    Public Overridable Function Get_Motivos() As ObjectResult(Of Get_Motivos_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Get_Motivos_Result)("Get_Motivos")
    End Function

    Public Overridable Function Get_Series(cobrador As String) As ObjectResult(Of Get_Series_Result)
        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Get_Series_Result)("Get_Series", cobradorParameter)
    End Function

    Public Overridable Function Get_Usuarios(mAC As String) As ObjectResult(Of Get_Usuarios_Result)
        Dim mACParameter As ObjectParameter = If(mAC IsNot Nothing, New ObjectParameter("MAC", mAC), New ObjectParameter("MAC", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Get_Usuarios_Result)("Get_Usuarios", mACParameter)
    End Function

    Public Overridable Function LIQUIDA_RECIBOS(codigo_Cobr As String, fecha As Nullable(Of Date)) As Integer
        Dim codigo_CobrParameter As ObjectParameter = If(codigo_Cobr IsNot Nothing, New ObjectParameter("Codigo_Cobr", codigo_Cobr), New ObjectParameter("Codigo_Cobr", GetType(String)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("LIQUIDA_RECIBOS", codigo_CobrParameter, fechaParameter)
    End Function

    Public Overridable Function LlenaClientes() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("LlenaClientes")
    End Function

    Public Overridable Function QUITAR_DUPLICADO(nUM As String) As Integer
        Dim nUMParameter As ObjectParameter = If(nUM IsNot Nothing, New ObjectParameter("NUM", nUM), New ObjectParameter("NUM", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("QUITAR_DUPLICADO", nUMParameter)
    End Function

    Public Overridable Function Sales_by_Year(beginning_Date As Nullable(Of Date), ending_Date As Nullable(Of Date)) As Integer
        Dim beginning_DateParameter As ObjectParameter = If(beginning_Date.HasValue, New ObjectParameter("Beginning_Date", beginning_Date), New ObjectParameter("Beginning_Date", GetType(Date)))

        Dim ending_DateParameter As ObjectParameter = If(ending_Date.HasValue, New ObjectParameter("Ending_Date", ending_Date), New ObjectParameter("Ending_Date", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Sales_by_Year", beginning_DateParameter, ending_DateParameter)
    End Function

    Public Overridable Function SalesByCategory(categoryName As String, ordYear As String) As Integer
        Dim categoryNameParameter As ObjectParameter = If(categoryName IsNot Nothing, New ObjectParameter("CategoryName", categoryName), New ObjectParameter("CategoryName", GetType(String)))

        Dim ordYearParameter As ObjectParameter = If(ordYear IsNot Nothing, New ObjectParameter("OrdYear", ordYear), New ObjectParameter("OrdYear", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("SalesByCategory", categoryNameParameter, ordYearParameter)
    End Function

    Public Overridable Function SP_CR_CobDiasLaborados(f1 As Nullable(Of Date), f2 As Nullable(Of Date), cobrador As String) As ObjectResult(Of SP_CR_CobDiasLaborados_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_CobDiasLaborados_Result)("SP_CR_CobDiasLaborados", f1Parameter, f2Parameter, cobradorParameter)
    End Function

    Public Overridable Function SP_CR_CobDiasLaboradosXLider(f1 As Nullable(Of Date), f2 As Nullable(Of Date), lider As String) As ObjectResult(Of SP_CR_CobDiasLaboradosXLider_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Dim liderParameter As ObjectParameter = If(lider IsNot Nothing, New ObjectParameter("Lider", lider), New ObjectParameter("Lider", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_CobDiasLaboradosXLider_Result)("SP_CR_CobDiasLaboradosXLider", f1Parameter, f2Parameter, liderParameter)
    End Function

    Public Overridable Function SP_CR_CobDiasLaboradosXLiderResumido(f1 As Nullable(Of Date), f2 As Nullable(Of Date), lider As String) As ObjectResult(Of SP_CR_CobDiasLaboradosXLiderResumido_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Dim liderParameter As ObjectParameter = If(lider IsNot Nothing, New ObjectParameter("Lider", lider), New ObjectParameter("Lider", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_CobDiasLaboradosXLiderResumido_Result)("SP_CR_CobDiasLaboradosXLiderResumido", f1Parameter, f2Parameter, liderParameter)
    End Function

    Public Overridable Function SP_CR_VS_MOV_CLIENTESVISITAS(cLIENTE As String) As ObjectResult(Of SP_CR_VS_MOV_CLIENTESVISITAS_Result)
        Dim cLIENTEParameter As ObjectParameter = If(cLIENTE IsNot Nothing, New ObjectParameter("CLIENTE", cLIENTE), New ObjectParameter("CLIENTE", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_VS_MOV_CLIENTESVISITAS_Result)("SP_CR_VS_MOV_CLIENTESVISITAS", cLIENTEParameter)
    End Function

    Public Overridable Function SP_MON_VISITAS(fecha1 As Nullable(Of Date), fecha2 As Nullable(Of Date), cobrador As String) As ObjectResult(Of SP_MON_VISITAS_Result)
        Dim fecha1Parameter As ObjectParameter = If(fecha1.HasValue, New ObjectParameter("Fecha1", fecha1), New ObjectParameter("Fecha1", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("Fecha2", fecha2), New ObjectParameter("Fecha2", GetType(Date)))

        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_MON_VISITAS_Result)("SP_MON_VISITAS", fecha1Parameter, fecha2Parameter, cobradorParameter)
    End Function

    Public Overridable Function SP_MON_Visitas_Detalle(fecha1 As Nullable(Of Date), fecha2 As Nullable(Of Date), cobrador As String) As ObjectResult(Of SP_MON_Visitas_Detalle_Result)
        Dim fecha1Parameter As ObjectParameter = If(fecha1.HasValue, New ObjectParameter("Fecha1", fecha1), New ObjectParameter("Fecha1", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("Fecha2", fecha2), New ObjectParameter("Fecha2", GetType(Date)))

        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_MON_Visitas_Detalle_Result)("SP_MON_Visitas_Detalle", fecha1Parameter, fecha2Parameter, cobradorParameter)
    End Function

    Public Overridable Function SP_VS_AgendaVisita(cliente As String, cobrador As String, fecha As Nullable(Of Date), usuario As String, gestion As String) As Integer
        Dim clienteParameter As ObjectParameter = If(cliente IsNot Nothing, New ObjectParameter("Cliente", cliente), New ObjectParameter("Cliente", GetType(String)))

        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(String)))

        Dim gestionParameter As ObjectParameter = If(gestion IsNot Nothing, New ObjectParameter("Gestion", gestion), New ObjectParameter("Gestion", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("SP_VS_AgendaVisita", clienteParameter, cobradorParameter, fechaParameter, usuarioParameter, gestionParameter)
    End Function

    Public Overridable Function Ten_Most_Expensive_Products() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Ten_Most_Expensive_Products")
    End Function

    Public Overridable Function VACACIONES_EMPLEADOS() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("VACACIONES_EMPLEADOS")
    End Function

    Public Overridable Function VIENEAGENDA(codigo_clie As String, nombre_clie As String, cONT_NUMERO As String, cONT_NUMCUO As String, cONT_VALCUO As Nullable(Of Decimal), cONT_SALDO As Nullable(Of Decimal), fECHA As String, hORA As String, vISITADO As String, nOTA As String, cVEAGE As String, cIERRE As String, liquida As String) As Integer
        Dim codigo_clieParameter As ObjectParameter = If(codigo_clie IsNot Nothing, New ObjectParameter("Codigo_clie", codigo_clie), New ObjectParameter("Codigo_clie", GetType(String)))

        Dim nombre_clieParameter As ObjectParameter = If(nombre_clie IsNot Nothing, New ObjectParameter("Nombre_clie", nombre_clie), New ObjectParameter("Nombre_clie", GetType(String)))

        Dim cONT_NUMEROParameter As ObjectParameter = If(cONT_NUMERO IsNot Nothing, New ObjectParameter("CONT_NUMERO", cONT_NUMERO), New ObjectParameter("CONT_NUMERO", GetType(String)))

        Dim cONT_NUMCUOParameter As ObjectParameter = If(cONT_NUMCUO IsNot Nothing, New ObjectParameter("CONT_NUMCUO", cONT_NUMCUO), New ObjectParameter("CONT_NUMCUO", GetType(String)))

        Dim cONT_VALCUOParameter As ObjectParameter = If(cONT_VALCUO.HasValue, New ObjectParameter("CONT_VALCUO", cONT_VALCUO), New ObjectParameter("CONT_VALCUO", GetType(Decimal)))

        Dim cONT_SALDOParameter As ObjectParameter = If(cONT_SALDO.HasValue, New ObjectParameter("CONT_SALDO", cONT_SALDO), New ObjectParameter("CONT_SALDO", GetType(Decimal)))

        Dim fECHAParameter As ObjectParameter = If(fECHA IsNot Nothing, New ObjectParameter("FECHA", fECHA), New ObjectParameter("FECHA", GetType(String)))

        Dim hORAParameter As ObjectParameter = If(hORA IsNot Nothing, New ObjectParameter("HORA", hORA), New ObjectParameter("HORA", GetType(String)))

        Dim vISITADOParameter As ObjectParameter = If(vISITADO IsNot Nothing, New ObjectParameter("VISITADO", vISITADO), New ObjectParameter("VISITADO", GetType(String)))

        Dim nOTAParameter As ObjectParameter = If(nOTA IsNot Nothing, New ObjectParameter("NOTA", nOTA), New ObjectParameter("NOTA", GetType(String)))

        Dim cVEAGEParameter As ObjectParameter = If(cVEAGE IsNot Nothing, New ObjectParameter("CVEAGE", cVEAGE), New ObjectParameter("CVEAGE", GetType(String)))

        Dim cIERREParameter As ObjectParameter = If(cIERRE IsNot Nothing, New ObjectParameter("CIERRE", cIERRE), New ObjectParameter("CIERRE", GetType(String)))

        Dim liquidaParameter As ObjectParameter = If(liquida IsNot Nothing, New ObjectParameter("liquida", liquida), New ObjectParameter("liquida", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("VIENEAGENDA", codigo_clieParameter, nombre_clieParameter, cONT_NUMEROParameter, cONT_NUMCUOParameter, cONT_VALCUOParameter, cONT_SALDOParameter, fECHAParameter, hORAParameter, vISITADOParameter, nOTAParameter, cVEAGEParameter, cIERREParameter, liquidaParameter)
    End Function

    Public Overridable Function VIENECORRELA(cveage As String, cod_zona As String, correla As Nullable(Of Decimal), cIERRE As String, liquida As String) As Integer
        Dim cveageParameter As ObjectParameter = If(cveage IsNot Nothing, New ObjectParameter("cveage", cveage), New ObjectParameter("cveage", GetType(String)))

        Dim cod_zonaParameter As ObjectParameter = If(cod_zona IsNot Nothing, New ObjectParameter("cod_zona", cod_zona), New ObjectParameter("cod_zona", GetType(String)))

        Dim correlaParameter As ObjectParameter = If(correla.HasValue, New ObjectParameter("correla", correla), New ObjectParameter("correla", GetType(Decimal)))

        Dim cIERREParameter As ObjectParameter = If(cIERRE IsNot Nothing, New ObjectParameter("CIERRE", cIERRE), New ObjectParameter("CIERRE", GetType(String)))

        Dim liquidaParameter As ObjectParameter = If(liquida IsNot Nothing, New ObjectParameter("liquida", liquida), New ObjectParameter("liquida", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("VIENECORRELA", cveageParameter, cod_zonaParameter, correlaParameter, cIERREParameter, liquidaParameter)
    End Function

    Public Overridable Function VIENELOGGPS(uSUARIO As String, fECHA As String, hORA As String, lATITUD As String, lONGITUD As String, mAC As String) As Integer
        Dim uSUARIOParameter As ObjectParameter = If(uSUARIO IsNot Nothing, New ObjectParameter("USUARIO", uSUARIO), New ObjectParameter("USUARIO", GetType(String)))

        Dim fECHAParameter As ObjectParameter = If(fECHA IsNot Nothing, New ObjectParameter("FECHA", fECHA), New ObjectParameter("FECHA", GetType(String)))

        Dim hORAParameter As ObjectParameter = If(hORA IsNot Nothing, New ObjectParameter("HORA", hORA), New ObjectParameter("HORA", GetType(String)))

        Dim lATITUDParameter As ObjectParameter = If(lATITUD IsNot Nothing, New ObjectParameter("LATITUD", lATITUD), New ObjectParameter("LATITUD", GetType(String)))

        Dim lONGITUDParameter As ObjectParameter = If(lONGITUD IsNot Nothing, New ObjectParameter("LONGITUD", lONGITUD), New ObjectParameter("LONGITUD", GetType(String)))

        Dim mACParameter As ObjectParameter = If(mAC IsNot Nothing, New ObjectParameter("MAC", mAC), New ObjectParameter("MAC", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("VIENELOGGPS", uSUARIOParameter, fECHAParameter, hORAParameter, lATITUDParameter, lONGITUDParameter, mACParameter)
    End Function

    Public Overridable Function VIENENOCOBRO(codigo_clie As String, nombre_clie As String, cONT_NUMERO As String, cOBRADOR As String, fECHA As String, hORA As String, cODMOTIVO As String, mOTIVO As String, lATITUD As String, lONGITUD As String, cIERRE As String, liquida As String) As Integer
        Dim codigo_clieParameter As ObjectParameter = If(codigo_clie IsNot Nothing, New ObjectParameter("Codigo_clie", codigo_clie), New ObjectParameter("Codigo_clie", GetType(String)))

        Dim nombre_clieParameter As ObjectParameter = If(nombre_clie IsNot Nothing, New ObjectParameter("Nombre_clie", nombre_clie), New ObjectParameter("Nombre_clie", GetType(String)))

        Dim cONT_NUMEROParameter As ObjectParameter = If(cONT_NUMERO IsNot Nothing, New ObjectParameter("CONT_NUMERO", cONT_NUMERO), New ObjectParameter("CONT_NUMERO", GetType(String)))

        Dim cOBRADORParameter As ObjectParameter = If(cOBRADOR IsNot Nothing, New ObjectParameter("COBRADOR", cOBRADOR), New ObjectParameter("COBRADOR", GetType(String)))

        Dim fECHAParameter As ObjectParameter = If(fECHA IsNot Nothing, New ObjectParameter("FECHA", fECHA), New ObjectParameter("FECHA", GetType(String)))

        Dim hORAParameter As ObjectParameter = If(hORA IsNot Nothing, New ObjectParameter("HORA", hORA), New ObjectParameter("HORA", GetType(String)))

        Dim cODMOTIVOParameter As ObjectParameter = If(cODMOTIVO IsNot Nothing, New ObjectParameter("CODMOTIVO", cODMOTIVO), New ObjectParameter("CODMOTIVO", GetType(String)))

        Dim mOTIVOParameter As ObjectParameter = If(mOTIVO IsNot Nothing, New ObjectParameter("MOTIVO", mOTIVO), New ObjectParameter("MOTIVO", GetType(String)))

        Dim lATITUDParameter As ObjectParameter = If(lATITUD IsNot Nothing, New ObjectParameter("LATITUD", lATITUD), New ObjectParameter("LATITUD", GetType(String)))

        Dim lONGITUDParameter As ObjectParameter = If(lONGITUD IsNot Nothing, New ObjectParameter("LONGITUD", lONGITUD), New ObjectParameter("LONGITUD", GetType(String)))

        Dim cIERREParameter As ObjectParameter = If(cIERRE IsNot Nothing, New ObjectParameter("CIERRE", cIERRE), New ObjectParameter("CIERRE", GetType(String)))

        Dim liquidaParameter As ObjectParameter = If(liquida IsNot Nothing, New ObjectParameter("liquida", liquida), New ObjectParameter("liquida", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("VIENENOCOBRO", codigo_clieParameter, nombre_clieParameter, cONT_NUMEROParameter, cOBRADORParameter, fECHAParameter, hORAParameter, cODMOTIVOParameter, mOTIVOParameter, lATITUDParameter, lONGITUDParameter, cIERREParameter, liquidaParameter)
    End Function

    Public Overridable Function VIENENOSUPER(codigo_clie As String, nombre_clie As String, cONT_NUMERO As String, cOBRADOR As String, fECHA As String, hORA As String, cODMOTIVO As String, mOTIVO As String, lATITUD As String, lONGITUD As String, cIERRE As String, liquida As String) As Integer
        Dim codigo_clieParameter As ObjectParameter = If(codigo_clie IsNot Nothing, New ObjectParameter("Codigo_clie", codigo_clie), New ObjectParameter("Codigo_clie", GetType(String)))

        Dim nombre_clieParameter As ObjectParameter = If(nombre_clie IsNot Nothing, New ObjectParameter("Nombre_clie", nombre_clie), New ObjectParameter("Nombre_clie", GetType(String)))

        Dim cONT_NUMEROParameter As ObjectParameter = If(cONT_NUMERO IsNot Nothing, New ObjectParameter("CONT_NUMERO", cONT_NUMERO), New ObjectParameter("CONT_NUMERO", GetType(String)))

        Dim cOBRADORParameter As ObjectParameter = If(cOBRADOR IsNot Nothing, New ObjectParameter("COBRADOR", cOBRADOR), New ObjectParameter("COBRADOR", GetType(String)))

        Dim fECHAParameter As ObjectParameter = If(fECHA IsNot Nothing, New ObjectParameter("FECHA", fECHA), New ObjectParameter("FECHA", GetType(String)))

        Dim hORAParameter As ObjectParameter = If(hORA IsNot Nothing, New ObjectParameter("HORA", hORA), New ObjectParameter("HORA", GetType(String)))

        Dim cODMOTIVOParameter As ObjectParameter = If(cODMOTIVO IsNot Nothing, New ObjectParameter("CODMOTIVO", cODMOTIVO), New ObjectParameter("CODMOTIVO", GetType(String)))

        Dim mOTIVOParameter As ObjectParameter = If(mOTIVO IsNot Nothing, New ObjectParameter("MOTIVO", mOTIVO), New ObjectParameter("MOTIVO", GetType(String)))

        Dim lATITUDParameter As ObjectParameter = If(lATITUD IsNot Nothing, New ObjectParameter("LATITUD", lATITUD), New ObjectParameter("LATITUD", GetType(String)))

        Dim lONGITUDParameter As ObjectParameter = If(lONGITUD IsNot Nothing, New ObjectParameter("LONGITUD", lONGITUD), New ObjectParameter("LONGITUD", GetType(String)))

        Dim cIERREParameter As ObjectParameter = If(cIERRE IsNot Nothing, New ObjectParameter("CIERRE", cIERRE), New ObjectParameter("CIERRE", GetType(String)))

        Dim liquidaParameter As ObjectParameter = If(liquida IsNot Nothing, New ObjectParameter("liquida", liquida), New ObjectParameter("liquida", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("VIENENOSUPER", codigo_clieParameter, nombre_clieParameter, cONT_NUMEROParameter, cOBRADORParameter, fECHAParameter, hORAParameter, cODMOTIVOParameter, mOTIVOParameter, lATITUDParameter, lONGITUDParameter, cIERREParameter, liquidaParameter)
    End Function

    Public Overridable Function VIENERECIBOS(num_doc As String, tdoc As String, rtipodoc As String, fecha_recib As Nullable(Of Date), rFECHA As Nullable(Of Date), rCONCEPTO As String, rCONCEP2 As String, rCAMBIO As Nullable(Of Decimal), por_lempira As Nullable(Of Decimal), rlugar As String, rhora As String, cOBRADO_EN As String, rtermino As String, codigo_clie As String, rcodigocli As String, cXC_CTIPO As String, cXC_PARTIDA As String, rusuario As String, rterminal As String, rECIBMODIFI As String, rECIBFMODIF As Nullable(Of Date), rduradeb As Nullable(Of Short), rTIPODEBI As String, rsucursal As String, codigo_cobr As String, rNOMBRECLI As String, rprima As Nullable(Of Decimal), rno_letras As Nullable(Of Short), vEFECTI As Nullable(Of Decimal), vCHEQUE As Nullable(Of Decimal), pAGOCK As String, pAGOBANCO As String, rECIBCUENTA As String, rconciliado As String, rnumefa As String, rCUOTA As Nullable(Of Decimal), sUBIVIEJO As String, rCODVEND As String, rnumemp As Nullable(Of Integer), lONGITUD As String, lATITUD As String, cIERRE As String, iMPRESO As String, mARCA As String, sALDOANT As Nullable(Of Decimal), fecha As String, liquida As String) As Integer
        Dim num_docParameter As ObjectParameter = If(num_doc IsNot Nothing, New ObjectParameter("Num_doc", num_doc), New ObjectParameter("Num_doc", GetType(String)))

        Dim tdocParameter As ObjectParameter = If(tdoc IsNot Nothing, New ObjectParameter("Tdoc", tdoc), New ObjectParameter("Tdoc", GetType(String)))

        Dim rtipodocParameter As ObjectParameter = If(rtipodoc IsNot Nothing, New ObjectParameter("rtipodoc", rtipodoc), New ObjectParameter("rtipodoc", GetType(String)))

        Dim fecha_recibParameter As ObjectParameter = If(fecha_recib.HasValue, New ObjectParameter("Fecha_recib", fecha_recib), New ObjectParameter("Fecha_recib", GetType(Date)))

        Dim rFECHAParameter As ObjectParameter = If(rFECHA.HasValue, New ObjectParameter("RFECHA", rFECHA), New ObjectParameter("RFECHA", GetType(Date)))

        Dim rCONCEPTOParameter As ObjectParameter = If(rCONCEPTO IsNot Nothing, New ObjectParameter("RCONCEPTO", rCONCEPTO), New ObjectParameter("RCONCEPTO", GetType(String)))

        Dim rCONCEP2Parameter As ObjectParameter = If(rCONCEP2 IsNot Nothing, New ObjectParameter("RCONCEP2", rCONCEP2), New ObjectParameter("RCONCEP2", GetType(String)))

        Dim rCAMBIOParameter As ObjectParameter = If(rCAMBIO.HasValue, New ObjectParameter("RCAMBIO", rCAMBIO), New ObjectParameter("RCAMBIO", GetType(Decimal)))

        Dim por_lempiraParameter As ObjectParameter = If(por_lempira.HasValue, New ObjectParameter("Por_lempira", por_lempira), New ObjectParameter("Por_lempira", GetType(Decimal)))

        Dim rlugarParameter As ObjectParameter = If(rlugar IsNot Nothing, New ObjectParameter("rlugar", rlugar), New ObjectParameter("rlugar", GetType(String)))

        Dim rhoraParameter As ObjectParameter = If(rhora IsNot Nothing, New ObjectParameter("rhora", rhora), New ObjectParameter("rhora", GetType(String)))

        Dim cOBRADO_ENParameter As ObjectParameter = If(cOBRADO_EN IsNot Nothing, New ObjectParameter("COBRADO_EN", cOBRADO_EN), New ObjectParameter("COBRADO_EN", GetType(String)))

        Dim rterminoParameter As ObjectParameter = If(rtermino IsNot Nothing, New ObjectParameter("rtermino", rtermino), New ObjectParameter("rtermino", GetType(String)))

        Dim codigo_clieParameter As ObjectParameter = If(codigo_clie IsNot Nothing, New ObjectParameter("Codigo_clie", codigo_clie), New ObjectParameter("Codigo_clie", GetType(String)))

        Dim rcodigocliParameter As ObjectParameter = If(rcodigocli IsNot Nothing, New ObjectParameter("rcodigocli", rcodigocli), New ObjectParameter("rcodigocli", GetType(String)))

        Dim cXC_CTIPOParameter As ObjectParameter = If(cXC_CTIPO IsNot Nothing, New ObjectParameter("CXC_CTIPO", cXC_CTIPO), New ObjectParameter("CXC_CTIPO", GetType(String)))

        Dim cXC_PARTIDAParameter As ObjectParameter = If(cXC_PARTIDA IsNot Nothing, New ObjectParameter("CXC_PARTIDA", cXC_PARTIDA), New ObjectParameter("CXC_PARTIDA", GetType(String)))

        Dim rusuarioParameter As ObjectParameter = If(rusuario IsNot Nothing, New ObjectParameter("rusuario", rusuario), New ObjectParameter("rusuario", GetType(String)))

        Dim rterminalParameter As ObjectParameter = If(rterminal IsNot Nothing, New ObjectParameter("rterminal", rterminal), New ObjectParameter("rterminal", GetType(String)))

        Dim rECIBMODIFIParameter As ObjectParameter = If(rECIBMODIFI IsNot Nothing, New ObjectParameter("RECIBMODIFI", rECIBMODIFI), New ObjectParameter("RECIBMODIFI", GetType(String)))

        Dim rECIBFMODIFParameter As ObjectParameter = If(rECIBFMODIF.HasValue, New ObjectParameter("RECIBFMODIF", rECIBFMODIF), New ObjectParameter("RECIBFMODIF", GetType(Date)))

        Dim rduradebParameter As ObjectParameter = If(rduradeb.HasValue, New ObjectParameter("rduradeb", rduradeb), New ObjectParameter("rduradeb", GetType(Short)))

        Dim rTIPODEBIParameter As ObjectParameter = If(rTIPODEBI IsNot Nothing, New ObjectParameter("RTIPODEBI", rTIPODEBI), New ObjectParameter("RTIPODEBI", GetType(String)))

        Dim rsucursalParameter As ObjectParameter = If(rsucursal IsNot Nothing, New ObjectParameter("rsucursal", rsucursal), New ObjectParameter("rsucursal", GetType(String)))

        Dim codigo_cobrParameter As ObjectParameter = If(codigo_cobr IsNot Nothing, New ObjectParameter("codigo_cobr", codigo_cobr), New ObjectParameter("codigo_cobr", GetType(String)))

        Dim rNOMBRECLIParameter As ObjectParameter = If(rNOMBRECLI IsNot Nothing, New ObjectParameter("RNOMBRECLI", rNOMBRECLI), New ObjectParameter("RNOMBRECLI", GetType(String)))

        Dim rprimaParameter As ObjectParameter = If(rprima.HasValue, New ObjectParameter("rprima", rprima), New ObjectParameter("rprima", GetType(Decimal)))

        Dim rno_letrasParameter As ObjectParameter = If(rno_letras.HasValue, New ObjectParameter("rno_letras", rno_letras), New ObjectParameter("rno_letras", GetType(Short)))

        Dim vEFECTIParameter As ObjectParameter = If(vEFECTI.HasValue, New ObjectParameter("VEFECTI", vEFECTI), New ObjectParameter("VEFECTI", GetType(Decimal)))

        Dim vCHEQUEParameter As ObjectParameter = If(vCHEQUE.HasValue, New ObjectParameter("VCHEQUE", vCHEQUE), New ObjectParameter("VCHEQUE", GetType(Decimal)))

        Dim pAGOCKParameter As ObjectParameter = If(pAGOCK IsNot Nothing, New ObjectParameter("PAGOCK", pAGOCK), New ObjectParameter("PAGOCK", GetType(String)))

        Dim pAGOBANCOParameter As ObjectParameter = If(pAGOBANCO IsNot Nothing, New ObjectParameter("PAGOBANCO", pAGOBANCO), New ObjectParameter("PAGOBANCO", GetType(String)))

        Dim rECIBCUENTAParameter As ObjectParameter = If(rECIBCUENTA IsNot Nothing, New ObjectParameter("RECIBCUENTA", rECIBCUENTA), New ObjectParameter("RECIBCUENTA", GetType(String)))

        Dim rconciliadoParameter As ObjectParameter = If(rconciliado IsNot Nothing, New ObjectParameter("rconciliado", rconciliado), New ObjectParameter("rconciliado", GetType(String)))

        Dim rnumefaParameter As ObjectParameter = If(rnumefa IsNot Nothing, New ObjectParameter("rnumefa", rnumefa), New ObjectParameter("rnumefa", GetType(String)))

        Dim rCUOTAParameter As ObjectParameter = If(rCUOTA.HasValue, New ObjectParameter("RCUOTA", rCUOTA), New ObjectParameter("RCUOTA", GetType(Decimal)))

        Dim sUBIVIEJOParameter As ObjectParameter = If(sUBIVIEJO IsNot Nothing, New ObjectParameter("SUBIVIEJO", sUBIVIEJO), New ObjectParameter("SUBIVIEJO", GetType(String)))

        Dim rCODVENDParameter As ObjectParameter = If(rCODVEND IsNot Nothing, New ObjectParameter("RCODVEND", rCODVEND), New ObjectParameter("RCODVEND", GetType(String)))

        Dim rnumempParameter As ObjectParameter = If(rnumemp.HasValue, New ObjectParameter("rnumemp", rnumemp), New ObjectParameter("rnumemp", GetType(Integer)))

        Dim lONGITUDParameter As ObjectParameter = If(lONGITUD IsNot Nothing, New ObjectParameter("LONGITUD", lONGITUD), New ObjectParameter("LONGITUD", GetType(String)))

        Dim lATITUDParameter As ObjectParameter = If(lATITUD IsNot Nothing, New ObjectParameter("LATITUD", lATITUD), New ObjectParameter("LATITUD", GetType(String)))

        Dim cIERREParameter As ObjectParameter = If(cIERRE IsNot Nothing, New ObjectParameter("CIERRE", cIERRE), New ObjectParameter("CIERRE", GetType(String)))

        Dim iMPRESOParameter As ObjectParameter = If(iMPRESO IsNot Nothing, New ObjectParameter("IMPRESO", iMPRESO), New ObjectParameter("IMPRESO", GetType(String)))

        Dim mARCAParameter As ObjectParameter = If(mARCA IsNot Nothing, New ObjectParameter("MARCA", mARCA), New ObjectParameter("MARCA", GetType(String)))

        Dim sALDOANTParameter As ObjectParameter = If(sALDOANT.HasValue, New ObjectParameter("SALDOANT", sALDOANT), New ObjectParameter("SALDOANT", GetType(Decimal)))

        Dim fechaParameter As ObjectParameter = If(fecha IsNot Nothing, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(String)))

        Dim liquidaParameter As ObjectParameter = If(liquida IsNot Nothing, New ObjectParameter("liquida", liquida), New ObjectParameter("liquida", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("VIENERECIBOS", num_docParameter, tdocParameter, rtipodocParameter, fecha_recibParameter, rFECHAParameter, rCONCEPTOParameter, rCONCEP2Parameter, rCAMBIOParameter, por_lempiraParameter, rlugarParameter, rhoraParameter, cOBRADO_ENParameter, rterminoParameter, codigo_clieParameter, rcodigocliParameter, cXC_CTIPOParameter, cXC_PARTIDAParameter, rusuarioParameter, rterminalParameter, rECIBMODIFIParameter, rECIBFMODIFParameter, rduradebParameter, rTIPODEBIParameter, rsucursalParameter, codigo_cobrParameter, rNOMBRECLIParameter, rprimaParameter, rno_letrasParameter, vEFECTIParameter, vCHEQUEParameter, pAGOCKParameter, pAGOBANCOParameter, rECIBCUENTAParameter, rconciliadoParameter, rnumefaParameter, rCUOTAParameter, sUBIVIEJOParameter, rCODVENDParameter, rnumempParameter, lONGITUDParameter, lATITUDParameter, cIERREParameter, iMPRESOParameter, mARCAParameter, sALDOANTParameter, fechaParameter, liquidaParameter)
    End Function

    Public Overridable Function VIENERECIBOS_GD() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("VIENERECIBOS_GD")
    End Function

    Public Overridable Function VIENESUPERV(codigo_clie As String, nombre_clie As String, cONT_NUMERO As String, cOBRADOR As String, fECHA As String, hORA As String, cEDULA As String, bENEF1 As String, bENEF2 As String, bENEF3 As String, rTN As String, dIRECCION As String, lATITUD As String, lONGITUD As String, cIERRE As String, liquida As String) As Integer
        Dim codigo_clieParameter As ObjectParameter = If(codigo_clie IsNot Nothing, New ObjectParameter("Codigo_clie", codigo_clie), New ObjectParameter("Codigo_clie", GetType(String)))

        Dim nombre_clieParameter As ObjectParameter = If(nombre_clie IsNot Nothing, New ObjectParameter("Nombre_clie", nombre_clie), New ObjectParameter("Nombre_clie", GetType(String)))

        Dim cONT_NUMEROParameter As ObjectParameter = If(cONT_NUMERO IsNot Nothing, New ObjectParameter("CONT_NUMERO", cONT_NUMERO), New ObjectParameter("CONT_NUMERO", GetType(String)))

        Dim cOBRADORParameter As ObjectParameter = If(cOBRADOR IsNot Nothing, New ObjectParameter("COBRADOR", cOBRADOR), New ObjectParameter("COBRADOR", GetType(String)))

        Dim fECHAParameter As ObjectParameter = If(fECHA IsNot Nothing, New ObjectParameter("FECHA", fECHA), New ObjectParameter("FECHA", GetType(String)))

        Dim hORAParameter As ObjectParameter = If(hORA IsNot Nothing, New ObjectParameter("HORA", hORA), New ObjectParameter("HORA", GetType(String)))

        Dim cEDULAParameter As ObjectParameter = If(cEDULA IsNot Nothing, New ObjectParameter("CEDULA", cEDULA), New ObjectParameter("CEDULA", GetType(String)))

        Dim bENEF1Parameter As ObjectParameter = If(bENEF1 IsNot Nothing, New ObjectParameter("BENEF1", bENEF1), New ObjectParameter("BENEF1", GetType(String)))

        Dim bENEF2Parameter As ObjectParameter = If(bENEF2 IsNot Nothing, New ObjectParameter("BENEF2", bENEF2), New ObjectParameter("BENEF2", GetType(String)))

        Dim bENEF3Parameter As ObjectParameter = If(bENEF3 IsNot Nothing, New ObjectParameter("BENEF3", bENEF3), New ObjectParameter("BENEF3", GetType(String)))

        Dim rTNParameter As ObjectParameter = If(rTN IsNot Nothing, New ObjectParameter("RTN", rTN), New ObjectParameter("RTN", GetType(String)))

        Dim dIRECCIONParameter As ObjectParameter = If(dIRECCION IsNot Nothing, New ObjectParameter("DIRECCION", dIRECCION), New ObjectParameter("DIRECCION", GetType(String)))

        Dim lATITUDParameter As ObjectParameter = If(lATITUD IsNot Nothing, New ObjectParameter("LATITUD", lATITUD), New ObjectParameter("LATITUD", GetType(String)))

        Dim lONGITUDParameter As ObjectParameter = If(lONGITUD IsNot Nothing, New ObjectParameter("LONGITUD", lONGITUD), New ObjectParameter("LONGITUD", GetType(String)))

        Dim cIERREParameter As ObjectParameter = If(cIERRE IsNot Nothing, New ObjectParameter("CIERRE", cIERRE), New ObjectParameter("CIERRE", GetType(String)))

        Dim liquidaParameter As ObjectParameter = If(liquida IsNot Nothing, New ObjectParameter("liquida", liquida), New ObjectParameter("liquida", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("VIENESUPERV", codigo_clieParameter, nombre_clieParameter, cONT_NUMEROParameter, cOBRADORParameter, fECHAParameter, hORAParameter, cEDULAParameter, bENEF1Parameter, bENEF2Parameter, bENEF3Parameter, rTNParameter, dIRECCIONParameter, lATITUDParameter, lONGITUDParameter, cIERREParameter, liquidaParameter)
    End Function

End Class
