'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AREA
    Public Property Codigo_area As String
    Public Property Nombre_area As String
    Public Property a_usuario As String
    Public Property a_terminal As String
    Public Property AREA_mayori As Nullable(Of Decimal)
    Public Property area_proyec As Nullable(Of Decimal)
    Public Property area_public As Nullable(Of Decimal)

End Class
