'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BCOBPAG
    Public Property BCOPA_NUMER As String
    Public Property BCOPA_EYS As String
    Public Property BCOPA_TIPO As String
    Public Property BCOPA_FECDO As Nullable(Of Date)
    Public Property BNumero_cue As String
    Public Property BCOPA_CODIG As String
    Public Property BCOPA_NOMBR As String
    Public Property BCOPA_CONCE As String
    Public Property BCOPA_TOTAL As Nullable(Of Decimal)
    Public Property BCOPA_FECHA As Nullable(Of Date)
    Public Property BCOPA_COPAG As String

End Class
