'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CABBOR
    Public Property del_numero As String
    Public Property del_modulo As String
    Public Property del_tipo As String
    Public Property del_fec_reg As Nullable(Of Date)
    Public Property del_fec_bor As Nullable(Of Date)
    Public Property del_cuenta As String
    Public Property del_total As Nullable(Of Decimal)
    Public Property del_hora As String
    Public Property del_usuario As String
    Public Property del_cliente As String
    Public Property del_termina As String

End Class
