'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CABCAL
    Public Property CALCAL As String
    Public Property CAL_CFECHA As Nullable(Of Date)
    Public Property CAL_CNAGENC As String
    Public Property CAL_BL As String
    Public Property CAL_PROVEE As String
    Public Property cal_numfac As String
    Public Property CAL_CALTIPO As String
    Public Property CAL_COTROS As Nullable(Of Decimal)
    Public Property CAL_CAGENCI As String
    Public Property CAL_CVALOR As Nullable(Of Decimal)
    Public Property CAL_CIMPTO As Nullable(Of Decimal)
    Public Property CAL_CCAMBIO As Nullable(Of Decimal)
    Public Property CAL_CPAPELE As Nullable(Of Decimal)
    Public Property CAL_CTIMBRE As Nullable(Of Decimal)
    Public Property CAL_CCOMISI As Nullable(Of Decimal)
    Public Property CAL_CHONORA As Nullable(Of Decimal)
    Public Property CAL_CSEGURO As Nullable(Of Decimal)
    Public Property CAL_CCORRES As Nullable(Of Decimal)
    Public Property cal_cregist As Nullable(Of Decimal)
    Public Property CAL_CACARRE As Nullable(Of Decimal)
    Public Property CAL_CFLETE As Nullable(Of Decimal)
    Public Property CAL_EXTFLET As Nullable(Of Decimal)
    Public Property CAL_EXTSEGU As Nullable(Of Decimal)
    Public Property CAL_TOTDECR As Nullable(Of Decimal)
    Public Property cal_apagder As Nullable(Of Decimal)
    Public Property cal_apagimp As Nullable(Of Decimal)
    Public Property CAL_CSUPERV As Nullable(Of Decimal)
    Public Property cal_agente As String
    Public Property cal_ENP As Nullable(Of Decimal)
    Public Property cal_mozos As Nullable(Of Decimal)
    Public Property cal_pglobal As Nullable(Of Decimal)
    Public Property cal_usuario As String
    Public Property cal_termina As String
    Public Property cal_numpar As String
    Public Property cal_parage As String
    Public Property CAL_PARFLET As String
    Public Property CAL_PARDERE As String
    Public Property cal_porder As Nullable(Of Decimal)
    Public Property cal_porgas As Nullable(Of Decimal)
    Public Property CAL_SUCUR As String

End Class
