'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CABCOM
    Public Property cod_compani As String
    Public Property nombre_comp As String
    Public Property ultima_comp As Nullable(Of Short)
    Public Property exist_compa As Nullable(Of Decimal)
    Public Property exisf_compa As Nullable(Of Decimal)
    Public Property costop_comp As Nullable(Of Decimal)
    Public Property costfp_comp As Nullable(Of Decimal)
    Public Property costou_comp As Nullable(Of Decimal)
    Public Property costod_comp As Nullable(Of Decimal)
    Public Property CORRELPART As Nullable(Of Integer)

End Class
