'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CABFAC
    Public Property factpro As String
    Public Property factip As String
    Public Property facfecha As Nullable(Of Date)
    Public Property COD_PROYECT As String
    Public Property facnolin As Nullable(Of Short)
    Public Property factimprimi As String
    Public Property factot As Nullable(Of Decimal)
    Public Property FACIMPUES As Nullable(Of Decimal)
    Public Property factconcep As String

End Class
