'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAJRECI
    Public Property caj_numero As String
    Public Property caj_fecha As Nullable(Of Date)
    Public Property caj_valor As Nullable(Of Decimal)
    Public Property caj_cliente As String
    Public Property caj_nombre As String
    Public Property caj_concept As String
    Public Property caj_concep2 As String
    Public Property caj_cobrado As String
    Public Property caj_compa As String
    Public Property caj_sucurs As String
    Public Property CAJ_HORA As String
    Public Property CAJ_USUARIO As String

End Class
