'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CALENDAR
    Public Property CALITEM As Short
    Public Property CALEMPRE As String
    Public Property CALDIA As Short
    Public Property CALACREED As String
    Public Property CALDESCRI As String
    Public Property CALVALOR As Decimal
    Public Property CALCUENTA As String
    Public Property CALBANCO As String

End Class
