'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAPART
    Public Property CALCAL As String
    Public Property CAL_PARTIDA As String
    Public Property PORC_PARTID As Nullable(Of Decimal)
    Public Property CAL_ITEM As Nullable(Of Short)

End Class
