'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CLICOMEL
    Public Property Codigo_clie As String
    Public Property CLICOM_ITEM As Short
    Public Property CLICOM_FECH As Date
    Public Property CLICOM_COME As String
    Public Property CLICOM_USUA As String

End Class
