'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CMOVIM
    Public Property CCod_partid As String
    Public Property CNo_movimie As Short
    Public Property CFechamov As Nullable(Of Date)
    Public Property cuentacont As String
    Public Property CCodigo_cue As String
    Public Property cod_compani As String
    Public Property cano As Nullable(Of Short)
    Public Property cmes As Nullable(Of Short)
    Public Property cactuali As Nullable(Of Decimal)
    Public Property CCRODE As String
    Public Property CNum_doc As String
    Public Property CDebem As Nullable(Of Decimal)
    Public Property CHaberm As Nullable(Of Decimal)
    Public Property ccontrol As String
    Public Property CANOVIEJ As Nullable(Of Short)
    Public Property CMESVIEJ As Nullable(Of Short)
    Public Property cmopera As String
    Public Property cmovenla As String
    Public Property CPAR_CODIGO As String
    Public Property CPAR_NOMBRE As String
    Public Property ccantidad As Nullable(Of Short)
    Public Property ccodinve As String
    Public Property cbodega As String
    Public Property csucu As String

End Class
