'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COMIVEN
    Public Property CMV_ITEM As Short
    Public Property CMV_DESDEVA As Decimal
    Public Property CMV_HASTAVA As Decimal
    Public Property CMV_PORCENT As Decimal

End Class
