'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CONTRAT1
    Public Property CONT_NUMERO As String
    Public Property CONT_DNUMER As String
    Public Property CONT_DVALOR As Nullable(Of Decimal)
    Public Property CONT_DCOBR As String
    Public Property CONT_DCODIG As String
    Public Property CONT_DFECHA As Nullable(Of Date)
    Public Property CONT_JARDIN As String
    Public Property CONT_LETRA As String
    Public Property CONT_NNUM As String
    Public Property CONT_DNOMBR As String
    Public Property CONT_DDESCR As String
    Public Property CONT_DENTRE As String
    Public Property CONT_DCLIEN As String
    Public Property CONT_BODEGA As String
    Public Property CONT_DCREDI As String
    Public Property CONT_DCANT As Nullable(Of Short)
    Public Property CONT_DOCTO As String
    Public Property CONT_DZONA As String
    Public Property CONT_LUGENT As String
    Public Property CONT_DFECNA As Nullable(Of Date)
    Public Property CONT_DIDENT As String
    Public Property CONT_DFECDE As Nullable(Of Date)
    Public Property CONT_DLUGNA As String
    Public Property CONT_DPAIS As String
    Public Property CONT_DPADRE As String
    Public Property CONT_DMADRE As String
    Public Property CONT_DDIREC As String
    Public Property CONT_DLUGDE As String
    Public Property CONT_DHORA As String
    Public Property CONT_DPAREN As String
    Public Property CONT_DCNOMB As String
    Public Property CONT_DSELEC As String
    Public Property CONT_DUSUAR As String
    Public Property FECHA1 As String
    Public Property HORA1 As String
    Public Property LAT1 As String
    Public Property LON1 As String
    Public Property OBSERVA1 As String
    Public Property USUARIO1 As String
    Public Property FIRMA1 As Byte()
    Public Property FECHA2 As String
    Public Property HORA2 As String
    Public Property LAT2 As String
    Public Property LON2 As String
    Public Property OBSERVA2 As String
    Public Property USUARIO2 As String
    Public Property FIRMA2 As Byte()
    Public Property FECHA3 As String
    Public Property HORA3 As String
    Public Property LAT3 As String
    Public Property LON3 As String
    Public Property OBSERVA3 As String
    Public Property USUARIO3 As String
    Public Property FIRMA3 As Byte()
    Public Property PASO As String

End Class
