'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CORRELAT
    Public Property cofact As String
    Public Property factuo As Nullable(Of Decimal)
    Public Property factuo2 As Nullable(Of Decimal)
    Public Property factuc As Nullable(Of Decimal)
    Public Property FACTUOI As Nullable(Of Decimal)
    Public Property FACTUCI As Nullable(Of Decimal)
    Public Property nlibera As Nullable(Of Integer)
    Public Property factnotape As Nullable(Of Decimal)
    Public Property NOTASPESO As Nullable(Of Decimal)
    Public Property COTCOMPRA As Nullable(Of Decimal)
    Public Property partidao As Nullable(Of Integer)
    Public Property partidac As Nullable(Of Integer)
    Public Property CORAJUPRO As Nullable(Of Decimal)
    Public Property CORTRAPRO As Nullable(Of Decimal)
    Public Property tcomprob As Nullable(Of Decimal)
    Public Property corrndo As Nullable(Of Decimal)
    Public Property corrndc As Nullable(Of Decimal)
    Public Property entregas As Nullable(Of Decimal)
    Public Property ncparque As Nullable(Of Decimal)
    Public Property ndparque As Nullable(Of Decimal)
    Public Property ncmemorial As Nullable(Of Decimal)
    Public Property ndmemorial As Nullable(Of Decimal)
    Public Property clientesp As Nullable(Of Decimal)
    Public Property clientesm As Nullable(Of Decimal)
    Public Property contratop As Nullable(Of Decimal)
    Public Property contratom As Nullable(Of Decimal)
    Public Property clientes4 As Nullable(Of Decimal)
    Public Property clientes3 As Nullable(Of Decimal)
    Public Property clientes2 As Nullable(Of Decimal)
    Public Property clientesp2 As Nullable(Of Decimal)
    Public Property entparq As Nullable(Of Decimal)
    Public Property entm04 As Nullable(Of Decimal)
    Public Property entm03 As Nullable(Of Decimal)
    Public Property entm02 As Nullable(Of Decimal)
    Public Property entm01 As Nullable(Of Decimal)
    Public Property entm05 As Nullable(Of Decimal)
    Public Property clientes5 As Nullable(Of Decimal)
    Public Property clientesd As Nullable(Of Decimal)
    Public Property contratoa As Nullable(Of Decimal)
    Public Property clientesa As Nullable(Of Decimal)
    Public Property factuan As Nullable(Of Decimal)

End Class
