'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COTIZA
    Public Property COD_PROYECT As String
    Public Property COT_ITEM As Short
    Public Property COT_CANT As Nullable(Of Short)
    Public Property cot_descu As Nullable(Of Short)
    Public Property COT_CARGUE As String
    Public Property cot_imp As Nullable(Of Decimal)
    Public Property COT_DESCRI As String
    Public Property COT_PRECIO As Nullable(Of Decimal)

End Class
