'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CUADRELE
    Public Property CUA_FECHA As Date
    Public Property CUA_COMPA As String
    Public Property CUA_SUCU As String
    Public Property CUA_ITEM As Short
    Public Property CUA_CUENTA As String
    Public Property CUA_BANCO As String
    Public Property CUA_CONCEPT As String
    Public Property CUA_VALOR As Nullable(Of Decimal)
    Public Property CUA_TIPO As String
    Public Property CUA_SUCURS As String
    Public Property CUA_ANGEL As String

End Class
