'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer_and_Suppliers_by_City
    Public Property City As String
    Public Property CompanyName As String
    Public Property ContactName As String
    Public Property Relationship As String

End Class
