'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DETCHK
    Public Property CALCAL As String
    Public Property cal_chkit As Short
    Public Property Cod_product As String
    Public Property chkdesc1 As Nullable(Of Short)
    Public Property chkdesc2 As Nullable(Of Short)
    Public Property chkdesc3 As Nullable(Of Short)
    Public Property chkcodigo As String
    Public Property chkcanti As Nullable(Of Decimal)
    Public Property chkdescri As String
    Public Property calcosto As Nullable(Of Decimal)
    Public Property calprecio As Nullable(Of Decimal)

End Class
