'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DETFAC
    Public Property factpro As String
    Public Property facitem As Short
    Public Property faccant As Nullable(Of Decimal)
    Public Property FACDESC As Nullable(Of Short)
    Public Property FACIMP As String
    Public Property FACIMPU As Nullable(Of Decimal)
    Public Property facdescri As String
    Public Property facpreci As Nullable(Of Decimal)

End Class
