'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DETSEG
    Public Property SEG_USUARIO As String
    Public Property SEG_ARCHIVO As String
    Public Property SEG_INS As String
    Public Property SEG_UPD As String
    Public Property SEG_DEL As String

End Class
