'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class FUNAMOREntities2
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FUNAMOREntities2")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property A_DEPA() As DbSet(Of A_DEPA)
    Public Overridable Property A_MAESTR() As DbSet(Of A_MAESTR)
    Public Overridable Property A_ZONA() As DbSet(Of A_ZONA)
    Public Overridable Property ADIBA2() As DbSet(Of ADIBA2)
    Public Overridable Property AREAS() As DbSet(Of AREA)
    Public Overridable Property ARMAPRO1() As DbSet(Of ARMAPRO1)
    Public Overridable Property ARMAPRODs() As DbSet(Of ARMAPROD)
    Public Overridable Property AUXPREs() As DbSet(Of AUXPRE)
    Public Overridable Property BBANCOS() As DbSet(Of BBANCO)
    Public Overridable Property BCHADIBAs() As DbSet(Of BCHADIBA)
    Public Overridable Property BCHNOPERs() As DbSet(Of BCHNOPER)
    Public Overridable Property BCHSALDOes() As DbSet(Of BCHSALDO)
    Public Overridable Property BCOBPAGs() As DbSet(Of BCOBPAG)
    Public Overridable Property BCONTRATs() As DbSet(Of BCONTRAT)
    Public Overridable Property BCUENTAS() As DbSet(Of BCUENTA)
    Public Overridable Property BODEGAS() As DbSet(Of BODEGA)
    Public Overridable Property CABBORs() As DbSet(Of CABBOR)
    Public Overridable Property CABCALs() As DbSet(Of CABCAL)
    Public Overridable Property CABCOMs() As DbSet(Of CABCOM)
    Public Overridable Property CABCONs() As DbSet(Of CABCON)
    Public Overridable Property CABEXIs() As DbSet(Of CABEXI)
    Public Overridable Property CABEXTs() As DbSet(Of CABEXT)
    Public Overridable Property CABFACs() As DbSet(Of CABFAC)
    Public Overridable Property CABLIS() As DbSet(Of CABLI)
    Public Overridable Property CABMOVIs() As DbSet(Of CABMOVI)
    Public Overridable Property CABMTIs() As DbSet(Of CABMTI)
    Public Overridable Property CABPROYs() As DbSet(Of CABPROY)
    Public Overridable Property CABSEGs() As DbSet(Of CABSEG)
    Public Overridable Property CAJRECIs() As DbSet(Of CAJRECI)
    Public Overridable Property CAJRECILs() As DbSet(Of CAJRECIL)
    Public Overridable Property CALENDARs() As DbSet(Of CALENDAR)
    Public Overridable Property CAMBFEs() As DbSet(Of CAMBFE)
    Public Overridable Property CAMBUBIs() As DbSet(Of CAMBUBI)
    Public Overridable Property CAPARTs() As DbSet(Of CAPART)
    Public Overridable Property CCONFIGs() As DbSet(Of CCONFIG)
    Public Overridable Property CCUENTs() As DbSet(Of CCUENT)
    Public Overridable Property CLCANCEs() As DbSet(Of CLCANCE)
    Public Overridable Property CLCIUDAs() As DbSet(Of CLCIUDA)
    Public Overridable Property CLICOBs() As DbSet(Of CLICOB)
    Public Overridable Property CLICOMELs() As DbSet(Of CLICOMEL)
    Public Overridable Property CLIENTES() As DbSet(Of CLIENTE)
    Public Overridable Property CMOVIMS() As DbSet(Of CMOVIM)
    Public Overridable Property COBCOBs() As DbSet(Of COBCOB)
    Public Overridable Property COBRADORs() As DbSet(Of COBRADOR)
    Public Overridable Property COBVISITs() As DbSet(Of COBVISIT)
    Public Overridable Property COCONCEs() As DbSet(Of COCONCE)
    Public Overridable Property COMIVENs() As DbSet(Of COMIVEN)
    Public Overridable Property CONTRAT1() As DbSet(Of CONTRAT1)
    Public Overridable Property CONTRATOes() As DbSet(Of CONTRATO)
    Public Overridable Property CORRELATs() As DbSet(Of CORRELAT)
    Public Overridable Property COTIZAs() As DbSet(Of COTIZA)
    Public Overridable Property COTVENTs() As DbSet(Of COTVENT)
    Public Overridable Property COTVENT1() As DbSet(Of COTVENT1)
    Public Overridable Property CPARTIDAs() As DbSet(Of CPARTIDA)
    Public Overridable Property CSALDOes() As DbSet(Of CSALDO)
    Public Overridable Property CUADREs() As DbSet(Of CUADRE)
    Public Overridable Property CUADRELEs() As DbSet(Of CUADRELE)
    Public Overridable Property CUENCOMPs() As DbSet(Of CUENCOMP)
    Public Overridable Property CZONAs() As DbSet(Of CZONA)
    Public Overridable Property DETBORs() As DbSet(Of DETBOR)
    Public Overridable Property DETCALs() As DbSet(Of DETCAL)
    Public Overridable Property DETCHKs() As DbSet(Of DETCHK)
    Public Overridable Property DETCONs() As DbSet(Of DETCON)
    Public Overridable Property DETEXTs() As DbSet(Of DETEXT)
    Public Overridable Property DETFACs() As DbSet(Of DETFAC)
    Public Overridable Property DETMAEs() As DbSet(Of DETMAE)
    Public Overridable Property DETMOVs() As DbSet(Of DETMOV)
    Public Overridable Property DETMTIs() As DbSet(Of DETMTI)
    Public Overridable Property DETPAGARs() As DbSet(Of DETPAGAR)
    Public Overridable Property DETPROes() As DbSet(Of DETPRO)
    Public Overridable Property DETRECIBs() As DbSet(Of DETRECIB)
    Public Overridable Property DETSEGs() As DbSet(Of DETSEG)
    Public Overridable Property DOCXCUs() As DbSet(Of DOCXCU)
    Public Overridable Property ENTREHIS() As DbSet(Of ENTREHI)
    Public Overridable Property EXIBODs() As DbSet(Of EXIBOD)
    Public Overridable Property FERIADOS() As DbSet(Of FERIADO)
    Public Overridable Property GestionCobroes() As DbSet(Of GestionCobro)
    Public Overridable Property HISTCLIs() As DbSet(Of HISTCLI)
    Public Overridable Property HISTVALEs() As DbSet(Of HISTVALE)
    Public Overridable Property HORASSEPs() As DbSet(Of HORASSEP)
    Public Overridable Property JARDINES() As DbSet(Of JARDINE)
    Public Overridable Property LISTP21() As DbSet(Of LISTP21)
    Public Overridable Property LogAccesoApps() As DbSet(Of LogAccesoApp)
    Public Overridable Property LogContrat1Web() As DbSet(Of LogContrat1Web)
    Public Overridable Property LogContratoWebs() As DbSet(Of LogContratoWeb)
    Public Overridable Property MAEPARs() As DbSet(Of MAEPAR)
    Public Overridable Property MATIBAs() As DbSet(Of MATIBA)
    Public Overridable Property MATICOes() As DbSet(Of MATICO)
    Public Overridable Property MATIINs() As DbSet(Of MATIIN)
    Public Overridable Property MOVCXCs() As DbSet(Of MOVCXC)
    Public Overridable Property MOVCXCLEs() As DbSet(Of MOVCXCLE)
    Public Overridable Property MULTICL1() As DbSet(Of MULTICL1)
    Public Overridable Property MULTICLIs() As DbSet(Of MULTICLI)
    Public Overridable Property NATURAs() As DbSet(Of NATURA)
    Public Overridable Property NRECIBOes() As DbSet(Of NRECIBO)
    Public Overridable Property OJARDLEVs() As DbSet(Of OJARDLEV)
    Public Overridable Property ORDENs() As DbSet(Of ORDEN)
    Public Overridable Property ORIGENs() As DbSet(Of ORIGEN)
    Public Overridable Property P_CIUDAD() As DbSet(Of P_CIUDAD)
    Public Overridable Property PAGARES() As DbSet(Of PAGARE)
    Public Overridable Property PAGCOMPs() As DbSet(Of PAGCOMP)
    Public Overridable Property PAPEVENLs() As DbSet(Of PAPEVENL)
    Public Overridable Property PERMIS() As DbSet(Of PERMI)
    Public Overridable Property PLACABs() As DbSet(Of PLACAB)
    Public Overridable Property PLACALs() As DbSet(Of PLACAL)
    Public Overridable Property PLACHIs() As DbSet(Of PLACHI)
    Public Overridable Property PLACONs() As DbSet(Of PLACON)
    Public Overridable Property PLACTAs() As DbSet(Of PLACTA)
    Public Overridable Property PLADEPs() As DbSet(Of PLADEP)
    Public Overridable Property PLADETs() As DbSet(Of PLADET)
    Public Overridable Property PLADHIs() As DbSet(Of PLADHI)
    Public Overridable Property PLADMAs() As DbSet(Of PLADMA)
    Public Overridable Property PLADTAs() As DbSet(Of PLADTA)
    Public Overridable Property PLAEMPs() As DbSet(Of PLAEMP)
    Public Overridable Property PLAHORs() As DbSet(Of PLAHOR)
    Public Overridable Property PLAINCAs() As DbSet(Of PLAINCA)
    Public Overridable Property PLAPUEs() As DbSet(Of PLAPUE)
    Public Overridable Property PLASUCs() As DbSet(Of PLASUC)
    Public Overridable Property PLAVACs() As DbSet(Of PLAVAC)
    Public Overridable Property PLDOCDEDs() As DbSet(Of PLDOCDED)
    Public Overridable Property PLOPAUTLs() As DbSet(Of PLOPAUTL)
    Public Overridable Property PMINIMOes() As DbSet(Of PMINIMO)
    Public Overridable Property POPERAs() As DbSet(Of POPERA)
    Public Overridable Property PPOPERs() As DbSet(Of PPOPER)
    Public Overridable Property PRESTAM1() As DbSet(Of PRESTAM1)
    Public Overridable Property PRESTAMOes() As DbSet(Of PRESTAMO)
    Public Overridable Property PRODUBICs() As DbSet(Of PRODUBIC)
    Public Overridable Property PRODUCTOes() As DbSet(Of PRODUCTO)
    Public Overridable Property PROEXIs() As DbSet(Of PROEXI)
    Public Overridable Property PROVEEDOes() As DbSet(Of PROVEEDO)
    Public Overridable Property PVALESLEs() As DbSet(Of PVALESLE)
    Public Overridable Property PZONAS() As DbSet(Of PZONA)
    Public Overridable Property RECIBOS() As DbSet(Of RECIBO)
    Public Overridable Property SEGARCs() As DbSet(Of SEGARC)
    Public Overridable Property SEPELIOS() As DbSet(Of SEPELIO)
    Public Overridable Property SERVCOSLs() As DbSet(Of SERVCOSL)
    Public Overridable Property SERVICI1() As DbSet(Of SERVICI1)
    Public Overridable Property SERVICIOs() As DbSet(Of SERVICIO)
    Public Overridable Property SERVINC1() As DbSet(Of SERVINC1)
    Public Overridable Property SERVINCLs() As DbSet(Of SERVINCL)
    Public Overridable Property SUBGRUs() As DbSet(Of SUBGRU)
    Public Overridable Property SUCFECs() As DbSet(Of SUCFEC)
    Public Overridable Property SUCFECLEs() As DbSet(Of SUCFECLE)
    Public Overridable Property SUCURSALs() As DbSet(Of SUCURSAL)
    Public Overridable Property SYSCONs() As DbSet(Of SYSCON)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property TECNICOS() As DbSet(Of TECNICO)
    Public Overridable Property UBICACs() As DbSet(Of UBICAC)
    Public Overridable Property UBIJARDs() As DbSet(Of UBIJARD)
    Public Overridable Property VALES() As DbSet(Of VALE)
    Public Overridable Property VALESLEVs() As DbSet(Of VALESLEV)
    Public Overridable Property VALTIPOS() As DbSet(Of VALTIPOS)
    Public Overridable Property VENDEDORs() As DbSet(Of VENDEDOR)
    Public Overridable Property VENDNULOes() As DbSet(Of VENDNULO)
    Public Overridable Property VZONAs() As DbSet(Of VZONA)
    Public Overridable Property ClientesH1() As DbSet(Of ClientesH1)
    Public Overridable Property ClientesH3() As DbSet(Of ClientesH3)
    Public Overridable Property CLIVISITs() As DbSet(Of CLIVISIT)
    Public Overridable Property Eventoes() As DbSet(Of Evento)
    Public Overridable Property EventoDets() As DbSet(Of EventoDet)
    Public Overridable Property EventoOlds() As DbSet(Of EventoOld)
    Public Overridable Property GXA0004() As DbSet(Of GXA0004)
    Public Overridable Property GXA0168() As DbSet(Of GXA0168)
    Public Overridable Property UrlClientes() As DbSet(Of UrlCliente)

    Public Overridable Function ActuaClientes(cOBRADOR As String) As Integer
        Dim cOBRADORParameter As ObjectParameter = If(cOBRADOR IsNot Nothing, New ObjectParameter("COBRADOR", cOBRADOR), New ObjectParameter("COBRADOR", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActuaClientes", cOBRADORParameter)
    End Function

    Public Overridable Function ActuaContrato(cOBRADOR As String) As Integer
        Dim cOBRADORParameter As ObjectParameter = If(cOBRADOR IsNot Nothing, New ObjectParameter("COBRADOR", cOBRADOR), New ObjectParameter("COBRADOR", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActuaContrato", cOBRADORParameter)
    End Function

    Public Overridable Function ActualizaPizarra() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActualizaPizarra")
    End Function

    Public Overridable Function ActualizaPizarraCobros() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ActualizaPizarraCobros")
    End Function

    Public Overridable Function CR_ESTADO_DE_CUENTA(cLIENTE As String) As ObjectResult(Of CR_ESTADO_DE_CUENTA_Result)
        Dim cLIENTEParameter As ObjectParameter = If(cLIENTE IsNot Nothing, New ObjectParameter("CLIENTE", cLIENTE), New ObjectParameter("CLIENTE", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CR_ESTADO_DE_CUENTA_Result)("CR_ESTADO_DE_CUENTA", cLIENTEParameter)
    End Function

    Public Overridable Function CR_SP_EntregasXFecha(fecha1 As Nullable(Of Date), fecha2 As Nullable(Of Date)) As ObjectResult(Of CR_SP_EntregasXFecha_Result)
        Dim fecha1Parameter As ObjectParameter = If(fecha1.HasValue, New ObjectParameter("fecha1", fecha1), New ObjectParameter("fecha1", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("fecha2", fecha2), New ObjectParameter("fecha2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CR_SP_EntregasXFecha_Result)("CR_SP_EntregasXFecha", fecha1Parameter, fecha2Parameter)
    End Function

    Public Overridable Function Estadistica_Visitas(f1 As Nullable(Of Date), f2 As Nullable(Of Date), lIDER As String) As Integer
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Dim lIDERParameter As ObjectParameter = If(lIDER IsNot Nothing, New ObjectParameter("LIDER", lIDER), New ObjectParameter("LIDER", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Estadistica_Visitas", f1Parameter, f2Parameter, lIDERParameter)
    End Function

    Public Overridable Function Guarda_Estadistica_Visitas() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Guarda_Estadistica_Visitas")
    End Function

    Public Overridable Function POSICIONES_COBRADORES(f1 As Nullable(Of Date), f2 As Nullable(Of Date)) As Integer
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("POSICIONES_COBRADORES", f1Parameter, f2Parameter)
    End Function

    Public Overridable Function POSICIONES_VENTAS(f1 As Nullable(Of Date), f2 As Nullable(Of Date)) As ObjectResult(Of POSICIONES_VENTAS_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of POSICIONES_VENTAS_Result)("POSICIONES_VENTAS", f1Parameter, f2Parameter)
    End Function

    Public Overridable Function POSICIONES_VENTAS_1(f1 As Nullable(Of Date), f2 As Nullable(Of Date)) As ObjectResult(Of POSICIONES_VENTAS_1_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of POSICIONES_VENTAS_1_Result)("POSICIONES_VENTAS_1", f1Parameter, f2Parameter)
    End Function

    Public Overridable Function POSICIONES_VENTAS_CATEGORIA(f1 As Nullable(Of Date), f2 As Nullable(Of Date), cat As String) As Integer
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Dim catParameter As ObjectParameter = If(cat IsNot Nothing, New ObjectParameter("Cat", cat), New ObjectParameter("Cat", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("POSICIONES_VENTAS_CATEGORIA", f1Parameter, f2Parameter, catParameter)
    End Function

    Public Overridable Function POSICIONES_VENTAS_LIDER(f1 As Nullable(Of Date), f2 As Nullable(Of Date)) As ObjectResult(Of POSICIONES_VENTAS_LIDER_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of POSICIONES_VENTAS_LIDER_Result)("POSICIONES_VENTAS_LIDER", f1Parameter, f2Parameter)
    End Function

    Public Overridable Function POSICIONES_VENTAS_LIDER_1(f1 As Nullable(Of Date), f2 As Nullable(Of Date)) As ObjectResult(Of POSICIONES_VENTAS_LIDER_1_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of POSICIONES_VENTAS_LIDER_1_Result)("POSICIONES_VENTAS_LIDER_1", f1Parameter, f2Parameter)
    End Function

    Public Overridable Function sp_alterdiagram(diagramname As String, owner_id As Nullable(Of Integer), version As Nullable(Of Integer), definition As Byte()) As Integer
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Dim versionParameter As ObjectParameter = If(version.HasValue, New ObjectParameter("version", version), New ObjectParameter("version", GetType(Integer)))

        Dim definitionParameter As ObjectParameter = If(definition IsNot Nothing, New ObjectParameter("definition", definition), New ObjectParameter("definition", GetType(Byte())))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter)
    End Function

    Public Overridable Function SP_CORREO_DescuentosAplicados() As ObjectResult(Of Nullable(Of Date))
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Date))("SP_CORREO_DescuentosAplicados")
    End Function

    Public Overridable Function SP_CR_MoraClientes(cliente As String) As ObjectResult(Of SP_CR_MoraClientes_Result)
        Dim clienteParameter As ObjectParameter = If(cliente IsNot Nothing, New ObjectParameter("Cliente", cliente), New ObjectParameter("Cliente", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_MoraClientes_Result)("SP_CR_MoraClientes", clienteParameter)
    End Function

    Public Overridable Function SP_CR_ReciboAppCobro(fecha As Nullable(Of Date), cOBRADOR As String, codigoCliente As String) As ObjectResult(Of SP_CR_ReciboAppCobro_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim cOBRADORParameter As ObjectParameter = If(cOBRADOR IsNot Nothing, New ObjectParameter("COBRADOR", cOBRADOR), New ObjectParameter("COBRADOR", GetType(String)))

        Dim codigoClienteParameter As ObjectParameter = If(codigoCliente IsNot Nothing, New ObjectParameter("CodigoCliente", codigoCliente), New ObjectParameter("CodigoCliente", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_ReciboAppCobro_Result)("SP_CR_ReciboAppCobro", fechaParameter, cOBRADORParameter, codigoClienteParameter)
    End Function

    Public Overridable Function SP_CR_VENTAS_P_REACTIV(fecha As Nullable(Of Date)) As ObjectResult(Of SP_CR_VENTAS_P_REACTIV_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_VENTAS_P_REACTIV_Result)("SP_CR_VENTAS_P_REACTIV", fechaParameter)
    End Function

    Public Overridable Function SP_CR_VentasPorFechaDetallado(f1 As Nullable(Of Date), f2 As Nullable(Of Date)) As ObjectResult(Of SP_CR_VentasPorFechaDetallado_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_VentasPorFechaDetallado_Result)("SP_CR_VentasPorFechaDetallado", f1Parameter, f2Parameter)
    End Function

    Public Overridable Function SP_CR_VentasPorFechaDetallado_lider(f1 As Nullable(Of Date), f2 As Nullable(Of Date), lider As String) As ObjectResult(Of SP_CR_VentasPorFechaDetallado_lider_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Dim liderParameter As ObjectParameter = If(lider IsNot Nothing, New ObjectParameter("Lider", lider), New ObjectParameter("Lider", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_VentasPorFechaDetallado_lider_Result)("SP_CR_VentasPorFechaDetallado_lider", f1Parameter, f2Parameter, liderParameter)
    End Function

    Public Overridable Function SP_CR_VentasPorFechaDetallado_Vendedor(f1 As Nullable(Of Date), f2 As Nullable(Of Date), vendedor As String) As ObjectResult(Of SP_CR_VentasPorFechaDetallado_Vendedor_Result)
        Dim f1Parameter As ObjectParameter = If(f1.HasValue, New ObjectParameter("F1", f1), New ObjectParameter("F1", GetType(Date)))

        Dim f2Parameter As ObjectParameter = If(f2.HasValue, New ObjectParameter("F2", f2), New ObjectParameter("F2", GetType(Date)))

        Dim vendedorParameter As ObjectParameter = If(vendedor IsNot Nothing, New ObjectParameter("Vendedor", vendedor), New ObjectParameter("Vendedor", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_VentasPorFechaDetallado_Vendedor_Result)("SP_CR_VentasPorFechaDetallado_Vendedor", f1Parameter, f2Parameter, vendedorParameter)
    End Function

    Public Overridable Function SP_CR_VS_MovimientoClineteSubRPT(cliente As String) As ObjectResult(Of SP_CR_VS_MovimientoClineteSubRPT_Result)
        Dim clienteParameter As ObjectParameter = If(cliente IsNot Nothing, New ObjectParameter("Cliente", cliente), New ObjectParameter("Cliente", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_CR_VS_MovimientoClineteSubRPT_Result)("SP_CR_VS_MovimientoClineteSubRPT", clienteParameter)
    End Function

    Public Overridable Function sp_creatediagram(diagramname As String, owner_id As Nullable(Of Integer), version As Nullable(Of Integer), definition As Byte()) As Integer
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Dim versionParameter As ObjectParameter = If(version.HasValue, New ObjectParameter("version", version), New ObjectParameter("version", GetType(Integer)))

        Dim definitionParameter As ObjectParameter = If(definition IsNot Nothing, New ObjectParameter("definition", definition), New ObjectParameter("definition", GetType(Byte())))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter)
    End Function

    Public Overridable Function sp_dropdiagram(diagramname As String, owner_id As Nullable(Of Integer)) As Integer
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter)
    End Function

    Public Overridable Function sp_helpdiagramdefinition(diagramname As String, owner_id As Nullable(Of Integer)) As ObjectResult(Of sp_helpdiagramdefinition_Result)
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_helpdiagramdefinition_Result)("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter)
    End Function

    Public Overridable Function sp_helpdiagrams(diagramname As String, owner_id As Nullable(Of Integer)) As ObjectResult(Of sp_helpdiagrams_Result)
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_helpdiagrams_Result)("sp_helpdiagrams", diagramnameParameter, owner_idParameter)
    End Function

    Public Overridable Function SP_PBI_CarteraCobrador(cobrador As String) As ObjectResult(Of SP_PBI_CarteraCobrador_Result)
        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_PBI_CarteraCobrador_Result)("SP_PBI_CarteraCobrador", cobradorParameter)
    End Function

    Public Overridable Function SP_PWI_EntregaServiciosCliente() As ObjectResult(Of SP_PWI_EntregaServiciosCliente_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_PWI_EntregaServiciosCliente_Result)("SP_PWI_EntregaServiciosCliente")
    End Function

    Public Overridable Function sp_renamediagram(diagramname As String, owner_id As Nullable(Of Integer), new_diagramname As String) As Integer
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Dim new_diagramnameParameter As ObjectParameter = If(new_diagramname IsNot Nothing, New ObjectParameter("new_diagramname", new_diagramname), New ObjectParameter("new_diagramname", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter)
    End Function

    Public Overridable Function SP_Task_CorrigeVentasContadoMesActual() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("SP_Task_CorrigeVentasContadoMesActual")
    End Function

    Public Overridable Function sp_upgraddiagrams() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_upgraddiagrams")
    End Function

    Public Overridable Function SP_VS_AnularClientePantallaServicios(cliente As String, usuario As String) As Integer
        Dim clienteParameter As ObjectParameter = If(cliente IsNot Nothing, New ObjectParameter("Cliente", cliente), New ObjectParameter("Cliente", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("SP_VS_AnularClientePantallaServicios", clienteParameter, usuarioParameter)
    End Function

    Public Overridable Function SP_VS_BuscarCorrelativoArchivoCliente(cliente As String) As ObjectResult(Of SP_VS_BuscarCorrelativoArchivoCliente_Result)
        Dim clienteParameter As ObjectParameter = If(cliente IsNot Nothing, New ObjectParameter("Cliente", cliente), New ObjectParameter("Cliente", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_VS_BuscarCorrelativoArchivoCliente_Result)("SP_VS_BuscarCorrelativoArchivoCliente", clienteParameter)
    End Function

    Public Overridable Function SP_VS_CambiaUBicacion(codigo_clie As String, jardin As String, ubicacion As String, letra As String, usuario As String) As Integer
        Dim codigo_clieParameter As ObjectParameter = If(codigo_clie IsNot Nothing, New ObjectParameter("Codigo_clie", codigo_clie), New ObjectParameter("Codigo_clie", GetType(String)))

        Dim jardinParameter As ObjectParameter = If(jardin IsNot Nothing, New ObjectParameter("Jardin", jardin), New ObjectParameter("Jardin", GetType(String)))

        Dim ubicacionParameter As ObjectParameter = If(ubicacion IsNot Nothing, New ObjectParameter("Ubicacion", ubicacion), New ObjectParameter("Ubicacion", GetType(String)))

        Dim letraParameter As ObjectParameter = If(letra IsNot Nothing, New ObjectParameter("letra", letra), New ObjectParameter("letra", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("SP_VS_CambiaUBicacion", codigo_clieParameter, jardinParameter, ubicacionParameter, letraParameter, usuarioParameter)
    End Function

    Public Overridable Function SP_VS_CrearNotaDuelo(codigoCliente As String, nombreCliente As String, difunto As String, idSala As String, sala As String, direccionSala As String, fechaVelacion As Nullable(Of Date), horaVelacion As String, direccionSepelio As String, fechaSepelio As Nullable(Of Date), horaSepelio As String, telefono As String, usuario As String) As ObjectResult(Of SP_VS_CrearNotaDuelo_Result)
        Dim codigoClienteParameter As ObjectParameter = If(codigoCliente IsNot Nothing, New ObjectParameter("CodigoCliente", codigoCliente), New ObjectParameter("CodigoCliente", GetType(String)))

        Dim nombreClienteParameter As ObjectParameter = If(nombreCliente IsNot Nothing, New ObjectParameter("NombreCliente", nombreCliente), New ObjectParameter("NombreCliente", GetType(String)))

        Dim difuntoParameter As ObjectParameter = If(difunto IsNot Nothing, New ObjectParameter("Difunto", difunto), New ObjectParameter("Difunto", GetType(String)))

        Dim idSalaParameter As ObjectParameter = If(idSala IsNot Nothing, New ObjectParameter("idSala", idSala), New ObjectParameter("idSala", GetType(String)))

        Dim salaParameter As ObjectParameter = If(sala IsNot Nothing, New ObjectParameter("Sala", sala), New ObjectParameter("Sala", GetType(String)))

        Dim direccionSalaParameter As ObjectParameter = If(direccionSala IsNot Nothing, New ObjectParameter("DireccionSala", direccionSala), New ObjectParameter("DireccionSala", GetType(String)))

        Dim fechaVelacionParameter As ObjectParameter = If(fechaVelacion.HasValue, New ObjectParameter("FechaVelacion", fechaVelacion), New ObjectParameter("FechaVelacion", GetType(Date)))

        Dim horaVelacionParameter As ObjectParameter = If(horaVelacion IsNot Nothing, New ObjectParameter("HoraVelacion", horaVelacion), New ObjectParameter("HoraVelacion", GetType(String)))

        Dim direccionSepelioParameter As ObjectParameter = If(direccionSepelio IsNot Nothing, New ObjectParameter("DireccionSepelio", direccionSepelio), New ObjectParameter("DireccionSepelio", GetType(String)))

        Dim fechaSepelioParameter As ObjectParameter = If(fechaSepelio.HasValue, New ObjectParameter("FechaSepelio", fechaSepelio), New ObjectParameter("FechaSepelio", GetType(Date)))

        Dim horaSepelioParameter As ObjectParameter = If(horaSepelio IsNot Nothing, New ObjectParameter("HoraSepelio", horaSepelio), New ObjectParameter("HoraSepelio", GetType(String)))

        Dim telefonoParameter As ObjectParameter = If(telefono IsNot Nothing, New ObjectParameter("Telefono", telefono), New ObjectParameter("Telefono", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_VS_CrearNotaDuelo_Result)("SP_VS_CrearNotaDuelo", codigoClienteParameter, nombreClienteParameter, difuntoParameter, idSalaParameter, salaParameter, direccionSalaParameter, fechaVelacionParameter, horaVelacionParameter, direccionSepelioParameter, fechaSepelioParameter, horaSepelioParameter, telefonoParameter, usuarioParameter)
    End Function

    Public Overridable Function SP_VS_CrearNotaDuelo_New(codigoCliente As String, nombreCliente As String, difunto As String, idSala As String, sala As String, direccionSala As String, fechaVelacion As Nullable(Of Date), horaVelacion As String, direccionSepelio As String, fechaSepelio As Nullable(Of Date), horaSepelio As String, telefono As String, sucursal As String, activo As Nullable(Of Boolean), estatus As Nullable(Of Boolean), usuario As String) As ObjectResult(Of SP_VS_CrearNotaDuelo_New_Result)
        Dim codigoClienteParameter As ObjectParameter = If(codigoCliente IsNot Nothing, New ObjectParameter("CodigoCliente", codigoCliente), New ObjectParameter("CodigoCliente", GetType(String)))

        Dim nombreClienteParameter As ObjectParameter = If(nombreCliente IsNot Nothing, New ObjectParameter("NombreCliente", nombreCliente), New ObjectParameter("NombreCliente", GetType(String)))

        Dim difuntoParameter As ObjectParameter = If(difunto IsNot Nothing, New ObjectParameter("Difunto", difunto), New ObjectParameter("Difunto", GetType(String)))

        Dim idSalaParameter As ObjectParameter = If(idSala IsNot Nothing, New ObjectParameter("idSala", idSala), New ObjectParameter("idSala", GetType(String)))

        Dim salaParameter As ObjectParameter = If(sala IsNot Nothing, New ObjectParameter("Sala", sala), New ObjectParameter("Sala", GetType(String)))

        Dim direccionSalaParameter As ObjectParameter = If(direccionSala IsNot Nothing, New ObjectParameter("DireccionSala", direccionSala), New ObjectParameter("DireccionSala", GetType(String)))

        Dim fechaVelacionParameter As ObjectParameter = If(fechaVelacion.HasValue, New ObjectParameter("FechaVelacion", fechaVelacion), New ObjectParameter("FechaVelacion", GetType(Date)))

        Dim horaVelacionParameter As ObjectParameter = If(horaVelacion IsNot Nothing, New ObjectParameter("HoraVelacion", horaVelacion), New ObjectParameter("HoraVelacion", GetType(String)))

        Dim direccionSepelioParameter As ObjectParameter = If(direccionSepelio IsNot Nothing, New ObjectParameter("DireccionSepelio", direccionSepelio), New ObjectParameter("DireccionSepelio", GetType(String)))

        Dim fechaSepelioParameter As ObjectParameter = If(fechaSepelio.HasValue, New ObjectParameter("FechaSepelio", fechaSepelio), New ObjectParameter("FechaSepelio", GetType(Date)))

        Dim horaSepelioParameter As ObjectParameter = If(horaSepelio IsNot Nothing, New ObjectParameter("HoraSepelio", horaSepelio), New ObjectParameter("HoraSepelio", GetType(String)))

        Dim telefonoParameter As ObjectParameter = If(telefono IsNot Nothing, New ObjectParameter("Telefono", telefono), New ObjectParameter("Telefono", GetType(String)))

        Dim sucursalParameter As ObjectParameter = If(sucursal IsNot Nothing, New ObjectParameter("Sucursal", sucursal), New ObjectParameter("Sucursal", GetType(String)))

        Dim activoParameter As ObjectParameter = If(activo.HasValue, New ObjectParameter("Activo", activo), New ObjectParameter("Activo", GetType(Boolean)))

        Dim estatusParameter As ObjectParameter = If(estatus.HasValue, New ObjectParameter("estatus", estatus), New ObjectParameter("estatus", GetType(Boolean)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_VS_CrearNotaDuelo_New_Result)("SP_VS_CrearNotaDuelo_New", codigoClienteParameter, nombreClienteParameter, difuntoParameter, idSalaParameter, salaParameter, direccionSalaParameter, fechaVelacionParameter, horaVelacionParameter, direccionSepelioParameter, fechaSepelioParameter, horaSepelioParameter, telefonoParameter, sucursalParameter, activoParameter, estatusParameter, usuarioParameter)
    End Function

    Public Overridable Function SP_VS_GestionCobro(codigo_clie As String, nombre_clie As String, cont_numero As String, cobrador As String, fecha As Nullable(Of Date), hora As String, codigoMotivo As Nullable(Of Integer), motivo As String, comentario As String, lider As String) As Integer
        Dim codigo_clieParameter As ObjectParameter = If(codigo_clie IsNot Nothing, New ObjectParameter("Codigo_clie", codigo_clie), New ObjectParameter("Codigo_clie", GetType(String)))

        Dim nombre_clieParameter As ObjectParameter = If(nombre_clie IsNot Nothing, New ObjectParameter("Nombre_clie", nombre_clie), New ObjectParameter("Nombre_clie", GetType(String)))

        Dim cont_numeroParameter As ObjectParameter = If(cont_numero IsNot Nothing, New ObjectParameter("Cont_numero", cont_numero), New ObjectParameter("Cont_numero", GetType(String)))

        Dim cobradorParameter As ObjectParameter = If(cobrador IsNot Nothing, New ObjectParameter("Cobrador", cobrador), New ObjectParameter("Cobrador", GetType(String)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim horaParameter As ObjectParameter = If(hora IsNot Nothing, New ObjectParameter("Hora", hora), New ObjectParameter("Hora", GetType(String)))

        Dim codigoMotivoParameter As ObjectParameter = If(codigoMotivo.HasValue, New ObjectParameter("CodigoMotivo", codigoMotivo), New ObjectParameter("CodigoMotivo", GetType(Integer)))

        Dim motivoParameter As ObjectParameter = If(motivo IsNot Nothing, New ObjectParameter("Motivo", motivo), New ObjectParameter("Motivo", GetType(String)))

        Dim comentarioParameter As ObjectParameter = If(comentario IsNot Nothing, New ObjectParameter("Comentario", comentario), New ObjectParameter("Comentario", GetType(String)))

        Dim liderParameter As ObjectParameter = If(lider IsNot Nothing, New ObjectParameter("Lider", lider), New ObjectParameter("Lider", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("SP_VS_GestionCobro", codigo_clieParameter, nombre_clieParameter, cont_numeroParameter, cobradorParameter, fechaParameter, horaParameter, codigoMotivoParameter, motivoParameter, comentarioParameter, liderParameter)
    End Function

    Public Overridable Function SP_VS_GuardarImagenRuta(cliente As String, hora As String, comentario As String, imagen As String, usuario As String, estado As Nullable(Of Boolean), nombreArchivo As String, ruta As String, nameFileCorrelativo As String) As Integer
        Dim clienteParameter As ObjectParameter = If(cliente IsNot Nothing, New ObjectParameter("Cliente", cliente), New ObjectParameter("Cliente", GetType(String)))

        Dim horaParameter As ObjectParameter = If(hora IsNot Nothing, New ObjectParameter("Hora", hora), New ObjectParameter("Hora", GetType(String)))

        Dim comentarioParameter As ObjectParameter = If(comentario IsNot Nothing, New ObjectParameter("Comentario", comentario), New ObjectParameter("Comentario", GetType(String)))

        Dim imagenParameter As ObjectParameter = If(imagen IsNot Nothing, New ObjectParameter("imagen", imagen), New ObjectParameter("imagen", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(String)))

        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("Estado", estado), New ObjectParameter("Estado", GetType(Boolean)))

        Dim nombreArchivoParameter As ObjectParameter = If(nombreArchivo IsNot Nothing, New ObjectParameter("NombreArchivo", nombreArchivo), New ObjectParameter("NombreArchivo", GetType(String)))

        Dim rutaParameter As ObjectParameter = If(ruta IsNot Nothing, New ObjectParameter("Ruta", ruta), New ObjectParameter("Ruta", GetType(String)))

        Dim nameFileCorrelativoParameter As ObjectParameter = If(nameFileCorrelativo IsNot Nothing, New ObjectParameter("NameFileCorrelativo", nameFileCorrelativo), New ObjectParameter("NameFileCorrelativo", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("SP_VS_GuardarImagenRuta", clienteParameter, horaParameter, comentarioParameter, imagenParameter, usuarioParameter, estadoParameter, nombreArchivoParameter, rutaParameter, nameFileCorrelativoParameter)
    End Function

    Public Overridable Function SP_VS_PantallaServicios() As ObjectResult(Of SP_VS_PantallaServicios_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_VS_PantallaServicios_Result)("SP_VS_PantallaServicios")
    End Function

End Class
