'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GestionCobro
    Public Property idLine As Integer
    Public Property Codigo_clie As String
    Public Property Nombre_clie As String
    Public Property Cont_numero As String
    Public Property Cobrador As String
    Public Property Fecha As Nullable(Of Date)
    Public Property Hora As String
    Public Property CodigoMotivo As Nullable(Of Integer)
    Public Property Motivo As String
    Public Property Comentario As String
    Public Property Lider As String

End Class
