'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HISTCLI
    Public Property HISTC_CODIG As String
    Public Property HISTC_FECHA As Date
    Public Property HISTC_HORA As String
    Public Property HISTC_TERMI As String
    Public Property HISTC_NOMAN As String
    Public Property HISTC_NOMAC As String

End Class
