'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Invoice
    Public Property ShipName As String
    Public Property ShipAddress As String
    Public Property ShipCity As String
    Public Property ShipRegion As String
    Public Property ShipPostalCode As String
    Public Property ShipCountry As String
    Public Property CustomerID As String
    Public Property CustomerName As String
    Public Property Address As String
    Public Property City As String
    Public Property Region As String
    Public Property PostalCode As String
    Public Property Country As String
    Public Property Salesperson As String
    Public Property OrderID As Integer
    Public Property OrderDate As Nullable(Of Date)
    Public Property RequiredDate As Nullable(Of Date)
    Public Property ShippedDate As Nullable(Of Date)
    Public Property ShipperName As String
    Public Property ProductID As Integer
    Public Property ProductName As String
    Public Property UnitPrice As Decimal
    Public Property Quantity As Short
    Public Property Discount As Single
    Public Property ExtendedPrice As Nullable(Of Decimal)
    Public Property Freight As Nullable(Of Decimal)

End Class
