'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LogProcesado
    Public Property IdLine As Integer
    Public Property Usuario As String
    Public Property Fecha As Nullable(Of Date)
    Public Property Hora As String
    Public Property CodGestor As String
    Public Property Liquida As String
    Public Property TotalProcesado As Nullable(Of Double)

End Class
