'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MOVCXC
    Public Property MOVCX_TIPO As String
    Public Property MOVCX_ITEM As String
    Public Property MOVCX_DESCR As String
    Public Property MOVCX_COBR As String

End Class
