'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ORDEN
    Public Property ORD_USUARIO As String
    Public Property ORD_TIPORE As String
    Public Property ORD_CODIGO As String
    Public Property ORD_VALOR As Decimal
    Public Property ORD_VALOR2 As Nullable(Of Decimal)
    Public Property ORD_PACTI As Nullable(Of Decimal)
    Public Property ORD_MACTI As Nullable(Of Decimal)
    Public Property ORD_VAL6 As Nullable(Of Decimal)
    Public Property ORD_VAL5 As Nullable(Of Decimal)

End Class
