'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order_Details_Extended
    Public Property OrderID As Integer
    Public Property ProductID As Integer
    Public Property ProductName As String
    Public Property UnitPrice As Decimal
    Public Property Quantity As Short
    Public Property Discount As Single
    Public Property ExtendedPrice As Nullable(Of Decimal)

End Class
