'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PAGARE
    Public Property Nump_doc As String
    Public Property Tdocp As String
    Public Property codprovee As String
    Public Property PCONCEPTO As String
    Public Property PCONCEP2 As String
    Public Property PCAMBIO As Nullable(Of Decimal)
    Public Property Fechap_reci As Nullable(Of Date)
    Public Property PFECHA As Nullable(Of Date)
    Public Property cxp_partida As String
    Public Property Porp_lempir As Nullable(Of Decimal)
    Public Property BNumero_cue As String
    Public Property CXP_CTIPO As String
    Public Property Cod_proveed As String
    Public Property pusuario As String
    Public Property pterminal As String
    Public Property PTERMINO As String
    Public Property PLUGAR As String
    Public Property PNACIOEXT As String
    Public Property PAGARMODIFI As String
    Public Property PAGARFMODIF As Nullable(Of Date)
    Public Property pconciliado As String
    Public Property PAGARBORRAD As String
    Public Property PAGARFBORRA As Nullable(Of Date)

End Class
