'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PAGCOMP
    Public Property Numero_docu As String
    Public Property Eys As String
    Public Property Tipodoc As String
    Public Property PAGC_ITEM As Short
    Public Property PAGC_PROVEE As String
    Public Property PAGC_FECHA As Nullable(Of Date)
    Public Property PAGC_VALOR As Nullable(Of Decimal)

End Class
