'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLACAB
    Public Property P_num_plani As String
    Public Property P_f_inicio As Nullable(Of Date)
    Public Property p_desdefech As Nullable(Of Date)
    Public Property p_hastafech As Nullable(Of Date)
    Public Property P_cod_plani As String
    Public Property p_cerrada As String
    Public Property pla_partida As String
    Public Property pla_comdesd As Nullable(Of Date)
    Public Property pla_comhast As Nullable(Of Date)
    Public Property P_MODIFICAD As String
    Public Property p_pagsegu As String
    Public Property p_placomis As String
    Public Property p_pselplan As String

End Class
