'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLACAL
    Public Property P_num_plani As String
    Public Property P_num_emple As Integer
    Public Property P_fecha As Date
    Public Property p_nombdia As String
    Public Property P_hora_entr As Nullable(Of Decimal)
    Public Property p_hora2_sal As Nullable(Of Decimal)
    Public Property p_hora2_ent As Nullable(Of Decimal)
    Public Property P_hora_sali As Nullable(Of Decimal)
    Public Property P_horas_int As Nullable(Of Decimal)
    Public Property p_cubierta As String
    Public Property p_cubnomb As String

End Class
