'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLACON
    Public Property P_control As String
    Public Property P_empresa As String
    Public Property P_fosovi As Nullable(Of Decimal)
    Public Property P_numero_pa As String
    Public Property P_razon_soc As String
    Public Property P_tipo_empr As String
    Public Property P_sector As String
    Public Property P_actividad As String
    Public Property P_direccion As String
    Public Property P_telefono As String
    Public Property P_fax As String
    Public Property P_numero_fo As Nullable(Of Decimal)
    Public Property P_DEPRECIA As Nullable(Of Decimal)

End Class
