'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLACHI
    Public Property ph_numpla As String
    Public Property ph_fecha As Nullable(Of Date)
    Public Property ph_hastfec As Nullable(Of Date)
    Public Property ph_tipo As String

End Class
