'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLADET
    Public Property P_num_plani As String
    Public Property P_num_emple As Integer
    Public Property P_COMISON As Nullable(Of Decimal)
    Public Property P_Cuentcob As Nullable(Of Decimal)
    Public Property P_PRESTAMOS As Nullable(Of Decimal)
    Public Property P_ANTICIPO As Nullable(Of Decimal)
    Public Property p_fijacob As String
    Public Property p_deduauto As String
    Public Property P_RETMUNIC As Nullable(Of Decimal)
    Public Property P_TRANSPORT As Nullable(Of Decimal)
    Public Property P_ext25 As Nullable(Of Decimal)
    Public Property P_ext50 As Nullable(Of Decimal)
    Public Property P_ext75 As Nullable(Of Decimal)
    Public Property P_ext100 As Nullable(Of Decimal)
    Public Property p_sumardias As Nullable(Of Decimal)
    Public Property P_ausencia As Nullable(Of Decimal)
    Public Property p_sumediasc As Nullable(Of Short)
    Public Property P_PLAISR As Nullable(Of Decimal)
    Public Property P_AJUSTE As Nullable(Of Decimal)
    Public Property P_OBSERV As String
    Public Property p_ajustemin As Nullable(Of Decimal)
    Public Property P_ventasm01 As Nullable(Of Decimal)
    Public Property p_ventasm02 As Nullable(Of Decimal)
    Public Property p_ventasm03 As Nullable(Of Decimal)
    Public Property p_ventasm04 As Nullable(Of Decimal)
    Public Property p_ventasp01 As Nullable(Of Decimal)
    Public Property p_premiom01 As Nullable(Of Decimal)
    Public Property p_premiom02 As Nullable(Of Decimal)
    Public Property p_premiom03 As Nullable(Of Decimal)
    Public Property p_premiom04 As Nullable(Of Decimal)
    Public Property p_premiop01 As Nullable(Of Decimal)
    Public Property p_reacanm01 As Nullable(Of Decimal)
    Public Property p_reacanm02 As Nullable(Of Decimal)
    Public Property p_reacanm03 As Nullable(Of Decimal)
    Public Property p_reacanm04 As Nullable(Of Decimal)
    Public Property p_reacanp01 As Nullable(Of Decimal)
    Public Property P_SUBINGRE As Nullable(Of Decimal)
    Public Property p_cxcm01 As Nullable(Of Decimal)
    Public Property p_cxcm02 As Nullable(Of Decimal)
    Public Property p_cxcm03 As Nullable(Of Decimal)
    Public Property p_cxcm04 As Nullable(Of Decimal)
    Public Property p_cxcp01 As Nullable(Of Decimal)
    Public Property P_SUBEGRE As Nullable(Of Decimal)
    Public Property P_SUPJAR As Nullable(Of Short)
    Public Property P_SUPMEM As Nullable(Of Short)
    Public Property P_VENTJAR As Nullable(Of Decimal)
    Public Property P_VENTMEM As Nullable(Of Decimal)
    Public Property P_MVALCOBR As Nullable(Of Decimal)
    Public Property P_JVALCOBR As Nullable(Of Decimal)
    Public Property P_SALDOANT As Nullable(Of Decimal)
    Public Property P_ULTIMEM As String
    Public Property P_ULTIJAR As String
    Public Property P_CUEBAN As String
    Public Property P_NUMCHEQ As String
    Public Property P_letramoto As Nullable(Of Decimal)
    Public Property p_numletmo As String
    Public Property p_combustib As Nullable(Of Decimal)
    Public Property p_fechapago As Nullable(Of Date)
    Public Property p_compa As String
    Public Property P_SUCU As String
    Public Property p_pagdepre As String
    Public Property P_DIHSS As Nullable(Of Decimal)
    Public Property p_dvalcomb As Nullable(Of Decimal)
    Public Property p_cxcm05 As Nullable(Of Decimal)
    Public Property p_reacanm05 As Nullable(Of Decimal)
    Public Property p_premiom05 As Nullable(Of Decimal)
    Public Property p_ventasm05 As Nullable(Of Decimal)

End Class
