'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLAINCA
    Public Property P_n_incapac As Integer
    Public Property P_num_emple As Nullable(Of Integer)
    Public Property P_f_incapac As Nullable(Of Date)
    Public Property P_t_incapac As String
    Public Property P_d_incapac As Nullable(Of Short)
    Public Property P_incobs1 As String
    Public Property P_incobs2 As String

End Class
