'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PLDOCDED
    Public Property PLD_NUMERO As String
    Public Property PLD_FECHA As Nullable(Of Date)
    Public Property P_num_emple As Nullable(Of Integer)
    Public Property PLD_VALOR As Nullable(Of Decimal)
    Public Property PLD_DEDUCIR As Nullable(Of Decimal)
    Public Property PLD_PARTIDA As String
    Public Property PLD_CONCEPT As String
    Public Property PLD_CODCONC As String
    Public Property PLD_CONC2 As String

End Class
