'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PROEXI
    Public Property codi_pro As String
    Public Property Cod_product As String
    Public Property PRODESCRI As String
    Public Property proexi1 As Nullable(Of Decimal)
    Public Property propdesc1 As Nullable(Of Short)
    Public Property propdesc2 As Nullable(Of Short)
    Public Property propdesc3 As Nullable(Of Short)
    Public Property PROPRECIO As Nullable(Of Decimal)

End Class
