'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PROVEEDO
    Public Property Cod_proveed As String
    Public Property Nombre_prov As String
    Public Property E_PROVEE As String
    Public Property cod_origen As String
    Public Property PCOD_ZONA As String
    Public Property cod_compani As String
    Public Property prov_sucurs As String
    Public Property PROV_COMPAN As String
    Public Property Tipo_provee As String
    Public Property Telef_prove As String
    Public Property fax_proveed As String
    Public Property Dir_proveed As String
    Public Property dir2_provee As String
    Public Property Saldop_actu As Nullable(Of Decimal)
    Public Property saldop_aL As Nullable(Of Decimal)
    Public Property saldop_c As Nullable(Of Decimal)
    Public Property saldop_cl As Nullable(Of Decimal)
    Public Property prov_usuari As String
    Public Property prov_termin As String
    Public Property prov_status As String
    Public Property PROV_RTN As String
    Public Property PROV_IDENTI As String
    Public Property PCIUDAD As String
    Public Property PCONTACTO As String
    Public Property PEMAIL As String

End Class
