'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RECIBOSDIA
    Public Property Num_doc As String
    Public Property Tdoc As String
    Public Property Fecha_recib As Nullable(Of Date)
    Public Property RCONCEPTO As String
    Public Property Por_lempira As Nullable(Of Decimal)
    Public Property COBRADO_EN As String
    Public Property Codigo_clie As String
    Public Property Nombre_clie As String
    Public Property CONT_NUMERO As String
    Public Property codigo_cobr As String
    Public Property RNOMBRECLI As String
    Public Property CIERRE As String
    Public Property liquida As String
    Public Property fecha As String
    Public Property MARCA As String
    Public Property LATITUD As Nullable(Of Decimal)
    Public Property LONGITUD As Nullable(Of Decimal)
    Public Property rterminal As String
    Public Property liquida2 As String

End Class
