'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sales_by_Category
    Public Property CategoryID As Integer
    Public Property CategoryName As String
    Public Property ProductName As String
    Public Property ProductSales As Nullable(Of Decimal)

End Class
