'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SERVCOSL
    Public Property serv_tipo As String
    Public Property serv_codigo As String
    Public Property serv_citem As Short
    Public Property serv_desfec As Date
    Public Property serv_hasfec As Date
    Public Property serv_costo As Decimal

End Class
