'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SUBGRU
    Public Property cod_subgru As String
    Public Property nomb_subgru As String
    Public Property SUBG_MAYORI As Nullable(Of Decimal)
    Public Property SUBG_PROYEC As Nullable(Of Decimal)
    Public Property SUBG_PUBLIC As Nullable(Of Decimal)

End Class
