'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SUCURSAL
    Public Property Codigo_sucu As String
    Public Property Nombre_sucu As String
    Public Property cod_compani As String
    Public Property Dir_sucursa As String
    Public Property Ciudad_sucu As String
    Public Property Telef_sucur As String
    Public Property Apart_sucur As String
    Public Property E_C_COBRAR As String
    Public Property E_V_CREDITO As String
    Public Property E_V_CONTADO As String
    Public Property E_I_S_VENTA As String
    Public Property E_C_GENERAL As String
    Public Property E_D_DIVERSO As String
    Public Property E_C_EMPLEAD As String
    Public Property E_COMPRAS As String
    Public Property E_I_S_COMPR As String
    Public Property E_C_PAGAR As String
    Public Property E_C_DOCUMEN As String
    Public Property E_C_PRESTAM As String
    Public Property E_C_BANCOS As String
    Public Property E_C_INTPRES As String
    Public Property EA_FINANCI As String
    Public Property EA_FLETES As String
    Public Property CORF_CAJA1 As Nullable(Of Integer)
    Public Property CORF_CAJA2 As Nullable(Of Integer)
    Public Property CORF_CAJA3 As Nullable(Of Integer)
    Public Property E_V_CONT2 As String
    Public Property EA_INVENTA As String
    Public Property requita As Nullable(Of Decimal)
    Public Property SUC_LETRA As String
    Public Property requient As Nullable(Of Decimal)
    Public Property ORDARMADO As Nullable(Of Decimal)
    Public Property trasla As Nullable(Of Decimal)
    Public Property sysbodega As String
    Public Property dir2_sucurs As String
    Public Property suc_rtn As String
    Public Property SUC_IMPC1 As String
    Public Property SUC_IMPC2 As String
    Public Property suc_totalco As Nullable(Of Decimal)

End Class
