'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SYSCON
    Public Property syscon1 As String
    Public Property DOLARCAMBIO As Nullable(Of Decimal)
    Public Property num_empresa As String
    Public Property nombre_empr As String
    Public Property clave_costo As String
    Public Property sysprecio As String
    Public Property syselimina As String
    Public Property sysmodifica As String
    Public Property syscosto As String
    Public Property sysexist As String
    Public Property syscxc As String
    Public Property SYSSUCURSAL As String
    Public Property sysdeclient As String
    Public Property syshaclient As String
    Public Property SYSCOMPANIA As String
    Public Property ULTIMAFACT As Nullable(Of Decimal)
    Public Property PREMIOMAYOR As Nullable(Of Decimal)
    Public Property PREMIOCONTA As Nullable(Of Integer)
    Public Property MANOBRA As Nullable(Of Decimal)
    Public Property COSTOSTOT As Nullable(Of Decimal)
    Public Property COSTOSIND As Nullable(Of Decimal)
    Public Property sysinvicex As Nullable(Of Decimal)
    Public Property sysinvicco As Nullable(Of Decimal)
    Public Property sysinvivex As Nullable(Of Decimal)
    Public Property sysinvivco As Nullable(Of Decimal)
    Public Property syscuenmano As String
    Public Property MORACXC As Nullable(Of Decimal)
    Public Property sysptcred As Nullable(Of Short)
    Public Property SYSCLAVE As String
    Public Property SYSFECHA As Nullable(Of Date)
    Public Property SYSFECHA1 As Nullable(Of Date)
    Public Property SYSCOMISION As String
    Public Property SYSBONOS As String
    Public Property SYSDEPRECIA As String
    Public Property SYSCOMBUS As String
    Public Property SYSCOMIOFI As String
    Public Property syscomiven As String
    Public Property sysbonoven As String
    Public Property sysviatven As String
    Public Property sysjsueldo As String
    Public Property sysjtrece As String
    Public Property sysjcator As String
    Public Property sysjbono As String
    Public Property syscsueldo As String
    Public Property syscbono As String
    Public Property sysctrece As String
    Public Property sysccator As String

End Class
