'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TECNICO
    Public Property cod_tecnico As Integer
    Public Property nombre_tecn As String
    Public Property TIPO_TECNIC As String
    Public Property empresa As String
    Public Property rtn As String
    Public Property tec_depto As String
    Public Property tec_jefeinm As String
    Public Property tec_jeferec As String
    Public Property tec_telefon As String
    Public Property tidentidad As String
    Public Property tec_status As String
    Public Property tec_usuario As String
    Public Property tec_inactiv As String
    Public Property tec_modific As String
    Public Property tec_fecmodi As Date
    Public Property TEC_TOPELI As Short
    Public Property tec_domicil As String
    Public Property tec_celular As String
    Public Property tec_telcasa As String
    Public Property tec_dirnego As String
    Public Property tec_cliepri As String
    Public Property tec_2cliepr As String
    Public Property tec_3cliepr As String
    Public Property TEC_SUCURSA As String
    Public Property TEC_PASAPOR As String

End Class
