'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UBIJARD
    Public Property UBIJ_JARDIN As String
    Public Property UBIJ_LINEA As Short
    Public Property UBIJ_COLUMN As Short
    Public Property UBIJ_LETRA As String
    Public Property UBIJ_NUMERO As String
    Public Property UBIJ_STATUS As String
    Public Property UBIJ_CLIENT As String

End Class
