'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VALESLEV
    Public Property VAL_EMPRESA As String
    Public Property VAL_NUMERO As Integer
    Public Property Codigo_clie As String
    Public Property VAL_DVALOR As Nullable(Of Decimal)

End Class
