'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class View_Vtas
    Public Property Codigo_clie As String
    Public Property Nombre_clie As String
    Public Property identidad As String
    Public Property tributario As String
    Public Property cl_fecha As Nullable(Of Date)
    Public Property CL_STATUS As String
    Public Property CL_COMPANIA As String
    Public Property Dir_cliente As String
    Public Property Dir2_client As String
    Public Property Dir3_client As String
    Public Property Dir4_client As String
    Public Property Dir5_client As String
    Public Property Telef_clien As String
    Public Property CL_CELULAR As String
    Public Property CL_EMAIL As String
    Public Property cl_conyunom As String
    Public Property cl_conyutel As String
    Public Property cl_conyudir As String
    Public Property CL_PARENt As String
    Public Property Cod_zona As String
    Public Property CL_VENDEDOR As String
    Public Property cl_usuario As String
    Public Property cl_terminal As String
    Public Property Expr2 As Nullable(Of Decimal)
    Public Property Expr3 As Nullable(Of Decimal)
    Public Property secuencia As Nullable(Of Integer)
    Public Property diavisita As Nullable(Of Short)
    Public Property semana As Nullable(Of Short)
    Public Property Expr4 As String
    Public Property Expr5 As String
    Public Property departa As String
    Public Property municipio As String
    Public Property circuito As String
    Public Property Expr6 As String
    Public Property Expr7 As String
    Public Property Expr8 As String
    Public Property Expr9 As String
    Public Property Expr10 As String
    Public Property Expr11 As String
    Public Property Expr12 As Nullable(Of Date)
    Public Property Expr13 As Nullable(Of Date)
    Public Property Expr14 As String
    Public Property Expr15 As String
    Public Property Expr16 As Nullable(Of Decimal)
    Public Property Expr17 As Nullable(Of Decimal)
    Public Property Expr18 As String
    Public Property Expr19 As String
    Public Property Expr20 As String
    Public Property Expr21 As String
    Public Property Expr22 As String
    Public Property Expr23 As String
    Public Property Expr24 As String
    Public Property Expr25 As String
    Public Property Expr26 As String
    Public Property Expr27 As String
    Public Property Expr28 As Nullable(Of Date)
    Public Property Expr29 As Nullable(Of Short)
    Public Property Expr30 As String
    Public Property Expr31 As String
    Public Property Expr32 As String
    Public Property Expr33 As String
    Public Property Expr34 As Nullable(Of Decimal)
    Public Property Expr35 As Nullable(Of Short)
    Public Property Expr36 As Nullable(Of Decimal)
    Public Property Expr37 As Nullable(Of Decimal)
    Public Property Expr38 As String
    Public Property Expr39 As String
    Public Property Expr40 As String
    Public Property Expr41 As String
    Public Property Expr42 As String
    Public Property Expr43 As Nullable(Of Decimal)
    Public Property Expr44 As String
    Public Property Expr45 As String
    Public Property Expr46 As Nullable(Of Integer)
    Public Property Expr47 As Nullable(Of Decimal)
    Public Property Expr48 As Nullable(Of Decimal)
    Public Property Expr49 As String
    Public Property Expr50 As String
    Public Property Expr51 As String
    Public Property Expr52 As Nullable(Of Decimal)
    Public Property Expr53 As String
    Public Property Expr54 As String
    Public Property Expr55 As String
    Public Property CONT_NUMERO As String
    Public Property CONT_FECHA As Nullable(Of Date)
    Public Property CONT_VALOR As Nullable(Of Decimal)
    Public Property CONT_CREDIT As String
    Public Property CONT_PRIMA As Nullable(Of Decimal)
    Public Property CONT_NUMCUO As Nullable(Of Short)
    Public Property CONT_VALCUO As Nullable(Of Decimal)
    Public Property cont_vended As String
    Public Property CONT_SERVI As String
    Public Property CONT_CANTI As Nullable(Of Short)
    Public Property CONT_COMPA As String
    Public Property CONT_CANT2 As Nullable(Of Short)
    Public Property CONT_SERV2 As String
    Public Property CONT_CANT3 As Nullable(Of Short)
    Public Property CONT_SERV3 As String
    Public Property CONT_CANT4 As Nullable(Of Short)
    Public Property CONT_SERV4 As String
    Public Property CONT_SVAL1 As Nullable(Of Decimal)
    Public Property CONT_SVAL2 As Nullable(Of Decimal)
    Public Property CONT_SVAL3 As Nullable(Of Decimal)
    Public Property CONT_SVAL4 As Nullable(Of Decimal)
    Public Property VENTA As String
    Public Property TEMPO As String
    Public Property CEDULA As String
    Public Property SERVI1DES As String
    Public Property SERVI2DES As String
    Public Property SERVI3DES As String
    Public Property SERVI4DES As String
    Public Property SERVIEMPRE As String
    Public Property NOMCLIE As String
    Public Property CIERRE As String
    Public Property LIQUIDA As String
    Public Property FIRMA As Byte()
    Public Property FIRMA2 As Byte()
    Public Property Hora As String
    Public Property FechaDoc As String

End Class
