'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VZONA
    Public Property vzon_codigo As String
    Public Property vzon_nombre As String
    Public Property vzon_ciudad As String
    Public Property vzon_empres As String
    Public Property vzon_app As String

End Class
