//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_MAESTR
    {
        public string A_codigo { get; set; }
        public string cod_compani { get; set; }
        public string A_cod_zona { get; set; }
        public string a_marca { get; set; }
        public string A_Factura { get; set; }
        public string A_serie { get; set; }
        public string A_proveedor { get; set; }
        public string A_UBICA { get; set; }
        public string A_COD_DEPA { get; set; }
        public string A_UBICAINI { get; set; }
        public string A_RESPOINI { get; set; }
        public string A_responsab { get; set; }
        public Nullable<decimal> A_valor_adq { get; set; }
        public Nullable<decimal> A_valor_res { get; set; }
        public Nullable<decimal> A_vida_util { get; set; }
        public Nullable<System.DateTime> A_fecha_adq { get; set; }
        public Nullable<decimal> A_dep_diari { get; set; }
        public Nullable<decimal> A_dep_mensu { get; set; }
        public Nullable<decimal> A_dep_anual { get; set; }
        public string A_sucursal { get; set; }
        public Nullable<decimal> A_dep_acumu { get; set; }
        public Nullable<decimal> A_valor_lib { get; set; }
        public string A_partida { get; set; }
        public string A_ctacont { get; set; }
        public string A_nombre { get; set; }
        public string A_status { get; set; }
        public Nullable<System.DateTime> A_fecha_ret { get; set; }
        public string A_motivo { get; set; }
        public Nullable<decimal> A_val_retir { get; set; }
        public string A_doc_retir { get; set; }
        public byte[] a_blob { get; set; }
    }
}
