//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADIBA2
    {
        public string BNumcuenta { get; set; }
        public string Bcod_tipo { get; set; }
        public string BNum_doc { get; set; }
        public string BNumero_cue { get; set; }
        public string busuario { get; set; }
        public string bterminal { get; set; }
        public string bplanilla { get; set; }
        public Nullable<decimal> BLEMPIRAS { get; set; }
        public Nullable<System.DateTime> BFecha_mov { get; set; }
        public string BDescripcio { get; set; }
        public string BPor_concep { get; set; }
        public string bpor_conc2 { get; set; }
        public string bpor_conc3 { get; set; }
        public string bopero { get; set; }
        public string BStatus { get; set; }
        public Nullable<decimal> BDebe { get; set; }
        public Nullable<decimal> BHaber { get; set; }
        public string CCod_partid { get; set; }
        public Nullable<decimal> bcambmov { get; set; }
        public string BMOVIBORRAD { get; set; }
        public Nullable<System.DateTime> BMOVIFBORRA { get; set; }
        public string BMOVIMODIFI { get; set; }
        public Nullable<System.DateTime> BMOVIFMODIF { get; set; }
        public string BGENERADO { get; set; }
        public Nullable<System.DateTime> BFECHPOST { get; set; }
        public string BSELECCION { get; set; }
        public string Btransfcue { get; set; }
        public Nullable<System.DateTime> BFECHCONCIL { get; set; }
        public string BCODIGO { get; set; }
        public string bhoramov { get; set; }
        public Nullable<System.DateTime> bffecha { get; set; }
        public string bidentidad { get; set; }
    }
}
