//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUXPRE
    {
        public string AUXPRE_NUM { get; set; }
        public string AUXPRE_TIPO { get; set; }
        public string PREST_NUMER { get; set; }
        public Nullable<System.DateTime> AUXPRE_PFEC { get; set; }
        public Nullable<System.DateTime> AUXPRE_FECH { get; set; }
        public string AUXPRE_CONC { get; set; }
        public string AUXPRE_DIVI { get; set; }
        public Nullable<decimal> AUXPRE_DEBE { get; set; }
        public Nullable<decimal> AUXPRE_HABE { get; set; }
        public decimal AUXPRE_ICAM { get; set; }
        public string AUXPRE_PART { get; set; }
        public decimal auxpre_inte { get; set; }
        public string prest_moded { get; set; }
        public Nullable<decimal> AUXPRE_CAMB { get; set; }
        public string auxpre_ende { get; set; }
        public string AUXPRE_CUEN { get; set; }
    }
}
