//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBANCOS
    {
        public string BCodigo_ban { get; set; }
        public string BNombre_ban { get; set; }
        public string BDir_banco { get; set; }
        public string BTelef_banc { get; set; }
        public string bb_usuario { get; set; }
        public string bb_terminal { get; set; }
    }
}
