//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCOBPAG
    {
        public string BCOPA_NUMER { get; set; }
        public string BCOPA_EYS { get; set; }
        public string BCOPA_TIPO { get; set; }
        public Nullable<System.DateTime> BCOPA_FECDO { get; set; }
        public string BNumero_cue { get; set; }
        public string BCOPA_CODIG { get; set; }
        public string BCOPA_NOMBR { get; set; }
        public string BCOPA_CONCE { get; set; }
        public Nullable<decimal> BCOPA_TOTAL { get; set; }
        public Nullable<System.DateTime> BCOPA_FECHA { get; set; }
        public string BCOPA_COPAG { get; set; }
    }
}
