//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGAS
    {
        public string CODIGO_BODE { get; set; }
        public string TIPO_BODEGA { get; set; }
        public string NOMBRE_BODE { get; set; }
        public string Codigo_sucu { get; set; }
        public string bod_usuario { get; set; }
        public string bod_termina { get; set; }
        public string EA_INVCONT { get; set; }
        public string EA_DEVCOMP { get; set; }
        public string EA_MERTRAN { get; set; }
        public string EA_COSTOV { get; set; }
        public string EA_CUEINV { get; set; }
        public string BOD_STATUS { get; set; }
        public string BOD_COMPA { get; set; }
        public string BODLETRAS { get; set; }
        public Nullable<int> BODCORENT { get; set; }
        public Nullable<int> BODCSALIDAS { get; set; }
        public Nullable<int> BODCENTRADA { get; set; }
    }
}
