//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABBOR
    {
        public string del_numero { get; set; }
        public string del_modulo { get; set; }
        public string del_tipo { get; set; }
        public Nullable<System.DateTime> del_fec_reg { get; set; }
        public Nullable<System.DateTime> del_fec_bor { get; set; }
        public string del_cuenta { get; set; }
        public Nullable<decimal> del_total { get; set; }
        public string del_hora { get; set; }
        public string del_usuario { get; set; }
        public string del_cliente { get; set; }
        public string del_termina { get; set; }
    }
}
