//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABEXT
    {
        public string CAL_FACTURA { get; set; }
        public string CAL_EXTRAN { get; set; }
        public Nullable<System.DateTime> CAL_FFECHA { get; set; }
        public string cal_ctipo { get; set; }
        public string cal_tipo { get; set; }
        public Nullable<decimal> cal_cambio { get; set; }
        public Nullable<short> CALFA_ULTIM { get; set; }
        public Nullable<decimal> CAL_INCLUID { get; set; }
        public Nullable<decimal> cal_otros { get; set; }
        public string CAL_PEDIDO { get; set; }
        public Nullable<decimal> CAL_UTILIDA { get; set; }
        public Nullable<decimal> CAL_SEGURO { get; set; }
        public Nullable<decimal> cal_fflete { get; set; }
        public string Cod_proveed { get; set; }
        public string IMPORTPARTI { get; set; }
        public string calf_termin { get; set; }
        public string calf_usuari { get; set; }
        public Nullable<decimal> CAL_FTOT { get; set; }
    }
}
