//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABMOVI
    {
        public string Numero_docu { get; set; }
        public string Eys { get; set; }
        public string Tipodoc { get; set; }
        public string iterminal { get; set; }
        public Nullable<short> DESCUENTO { get; set; }
        public string inv_ctipo { get; set; }
        public string Detalle1 { get; set; }
        public string Detalle2 { get; set; }
        public Nullable<decimal> ARMAUNIDADE { get; set; }
        public string Codigo_sucu { get; set; }
        public string debod { get; set; }
        public string aparece { get; set; }
        public string ihora { get; set; }
        public Nullable<System.DateTime> Fecha_mov { get; set; }
        public Nullable<System.DateTime> FFECHA { get; set; }
        public string FPAGO { get; set; }
        public Nullable<short> Dura_fact { get; set; }
        public Nullable<decimal> Nuevop_sald { get; set; }
        public string Cod_proveed { get; set; }
        public string Credito { get; set; }
        public string inv_partida { get; set; }
        public string Nombre { get; set; }
        public string iusuario { get; set; }
        public string termino { get; set; }
        public Nullable<decimal> VALCHEQ { get; set; }
        public Nullable<short> cabmoultima { get; set; }
        public string cabmomodifi { get; set; }
        public Nullable<System.DateTime> cabmofmodif { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> DTOTAL_IMP { get; set; }
        public Nullable<decimal> Total_doc { get; set; }
        public Nullable<decimal> CAMBIO { get; set; }
        public string COD_PROYECT { get; set; }
        public string Codigo_clie { get; set; }
        public string iusuari2 { get; set; }
        public string DETALLE3 { get; set; }
        public string LUGAR { get; set; }
        public string IMPRIMIO { get; set; }
        public string cuentacuadr { get; set; }
        public string ORDEN { get; set; }
        public string numefac { get; set; }
        public Nullable<decimal> Nuevo_saldo { get; set; }
        public Nullable<decimal> prima { get; set; }
        public Nullable<short> no_letras { get; set; }
        public string iconciliado { get; set; }
        public string tarjetacre { get; set; }
        public string Cod_vendedo { get; set; }
        public string tipofac { get; set; }
        public string codigocli { get; set; }
        public Nullable<decimal> comision { get; set; }
        public string COD2_VEND { get; set; }
        public Nullable<decimal> EFECTIVO { get; set; }
        public Nullable<decimal> VALTARJE { get; set; }
        public string CABMOBANCO { get; set; }
        public string NUMCHEQ { get; set; }
        public string NUMCUEBA { get; set; }
        public string cabmoborrad { get; set; }
        public Nullable<System.DateTime> cabmofborra { get; set; }
        public string cabmoimprim { get; set; }
        public string NUMPEDI { get; set; }
        public string detalle4 { get; set; }
        public Nullable<short> no_lin { get; set; }
        public string ARMAPRODU { get; set; }
        public Nullable<System.DateTime> CABMOCKFEC { get; set; }
        public string PARA_CB { get; set; }
        public Nullable<int> cod_tecnico { get; set; }
        public Nullable<decimal> ajuimpu { get; set; }
        public string NUMAUTORI { get; set; }
        public string NUMTARJET { get; set; }
        public string CAJA { get; set; }
        public string cabmparabo { get; set; }
    }
}
