//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIVISIT
    {
        public string Codigo_clie { get; set; }
        public System.DateTime cliv_fecha { get; set; }
        public string cliv_hora { get; set; }
        public string cliv_coment { get; set; }
    }
}
