//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBRADOR
    {
        public string codigo_cobr { get; set; }
        public string nombre_cobr { get; set; }
        public string COBR_STATUS { get; set; }
        public string cob_telefo { get; set; }
        public string cob_zona { get; set; }
        public Nullable<System.DateTime> cob_fingre { get; set; }
        public string cob_lider { get; set; }
        public string COB_DIRECCI { get; set; }
        public Nullable<System.DateTime> COB_FECHING { get; set; }
        public string COB_SUPERVI { get; set; }
        public string COB_EMAIL { get; set; }
        public string COB_TELTRAB { get; set; }
        public string COB_IDENTID { get; set; }
        public Nullable<System.DateTime> COB_FECNAC { get; set; }
        public byte[] COB_FOTO { get; set; }
    }
}
