//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORRELAT
    {
        public string cofact { get; set; }
        public Nullable<decimal> factuo { get; set; }
        public Nullable<decimal> factuo2 { get; set; }
        public Nullable<decimal> factuc { get; set; }
        public Nullable<decimal> FACTUOI { get; set; }
        public Nullable<decimal> FACTUCI { get; set; }
        public Nullable<int> nlibera { get; set; }
        public Nullable<decimal> factnotape { get; set; }
        public Nullable<decimal> NOTASPESO { get; set; }
        public Nullable<decimal> COTCOMPRA { get; set; }
        public Nullable<int> partidao { get; set; }
        public Nullable<int> partidac { get; set; }
        public Nullable<decimal> CORAJUPRO { get; set; }
        public Nullable<decimal> CORTRAPRO { get; set; }
        public Nullable<decimal> tcomprob { get; set; }
        public Nullable<decimal> corrndo { get; set; }
        public Nullable<decimal> corrndc { get; set; }
        public Nullable<decimal> entregas { get; set; }
        public Nullable<decimal> ncparque { get; set; }
        public Nullable<decimal> ndparque { get; set; }
        public Nullable<decimal> ncmemorial { get; set; }
        public Nullable<decimal> ndmemorial { get; set; }
        public Nullable<decimal> clientesp { get; set; }
        public Nullable<decimal> clientesm { get; set; }
        public Nullable<decimal> contratop { get; set; }
        public Nullable<decimal> contratom { get; set; }
        public Nullable<decimal> clientes4 { get; set; }
        public Nullable<decimal> clientes3 { get; set; }
        public Nullable<decimal> clientes2 { get; set; }
        public Nullable<decimal> clientesp2 { get; set; }
        public Nullable<decimal> entparq { get; set; }
        public Nullable<decimal> entm04 { get; set; }
        public Nullable<decimal> entm03 { get; set; }
        public Nullable<decimal> entm02 { get; set; }
        public Nullable<decimal> entm01 { get; set; }
    }
}
