//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTIZA
    {
        public string COD_PROYECT { get; set; }
        public short COT_ITEM { get; set; }
        public Nullable<short> COT_CANT { get; set; }
        public Nullable<short> cot_descu { get; set; }
        public string COT_CARGUE { get; set; }
        public Nullable<decimal> cot_imp { get; set; }
        public string COT_DESCRI { get; set; }
        public Nullable<decimal> COT_PRECIO { get; set; }
    }
}
