//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTVENT
    {
        public string COTV_Numero { get; set; }
        public Nullable<System.DateTime> COTV_Fecha { get; set; }
        public Nullable<System.DateTime> COTV_FFECHA { get; set; }
        public string COTV_CLIENT { get; set; }
        public string Codigo_clie { get; set; }
        public string COTV_Nombre { get; set; }
        public string COTV_usuari { get; set; }
        public string COTV_termin { get; set; }
        public string COTV_hora { get; set; }
        public Nullable<short> COTV_ultima { get; set; }
        public string COTV_STATUS { get; set; }
        public string COTV_FACTUR { get; set; }
        public string COTVDet1 { get; set; }
        public string COTVDET2 { get; set; }
        public string Cod_vendedo { get; set; }
        public Nullable<decimal> COTVImpues { get; set; }
        public Nullable<decimal> COTVTOTAL { get; set; }
        public string COTV_TPCL { get; set; }
        public Nullable<int> cod_tecnico { get; set; }
        public string COTV_TIPO { get; set; }
    }
}
