//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CZONA
    {
        public string Cod_zona { get; set; }
        public string Nombre_zona { get; set; }
        public string E_ZONAS { get; set; }
        public string E_VENTAS { get; set; }
        public string E_DEVOLUC { get; set; }
        public string E_VENTAS2 { get; set; }
        public Nullable<int> ZON_NC { get; set; }
        public Nullable<int> ZON_ND { get; set; }
        public string descri_zona { get; set; }
        public string E_CAJA { get; set; }
        public string E_APARTA { get; set; }
        public string E_LETRAS { get; set; }
        public string E_PRIMA { get; set; }
        public string E_PAQUETE { get; set; }
        public string E_CXC { get; set; }
        public string E_CONTADO { get; set; }
        public Nullable<short> CZ_NUME { get; set; }
        public string E_RTN { get; set; }
    }
}
