//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETBOR
    {
        public string del_numero { get; set; }
        public string del_modulo { get; set; }
        public string del_tipo { get; set; }
        public string del_detalle { get; set; }
        public Nullable<decimal> del_cantida { get; set; }
        public Nullable<decimal> del_precio { get; set; }
        public string del_debhab { get; set; }
        public string del_bodega { get; set; }
        public string del_parabod { get; set; }
    }
}
