//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETCON
    {
        public string BNumero_con { get; set; }
        public short BNu_movcon { get; set; }
        public Nullable<System.DateTime> BFECHA_CON { get; set; }
        public string Bcod_tipo { get; set; }
        public string BNum_con { get; set; }
        public Nullable<decimal> BDebecon { get; set; }
        public Nullable<decimal> BHabercon { get; set; }
    }
}
