//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETEXT
    {
        public string CAL_FACTURA { get; set; }
        public short CALFA_ITEM { get; set; }
        public string Cod_product { get; set; }
        public string cal_num { get; set; }
        public string cal_proddes { get; set; }
        public string dnuevocodi { get; set; }
        public string COD_PPRODUC { get; set; }
        public string Icod_tipo { get; set; }
        public Nullable<decimal> CAL_CANTIDA { get; set; }
        public Nullable<decimal> CAL_SALDO { get; set; }
        public string CAL_BOD { get; set; }
        public string CAL_CARGAR { get; set; }
        public Nullable<decimal> cal_fader { get; set; }
        public string CAL_PARTIDA { get; set; }
        public string CALFAPARTID { get; set; }
        public string CAL_DECRETO { get; set; }
        public Nullable<decimal> CAL_PESO { get; set; }
        public Nullable<decimal> CAL_DOLARES { get; set; }
        public Nullable<decimal> cal_faltant { get; set; }
        public Nullable<decimal> cal_sobrant { get; set; }
        public Nullable<decimal> cal_costo { get; set; }
        public Nullable<decimal> cal_rcosto { get; set; }
        public Nullable<decimal> CAL_SUBTOT { get; set; }
    }
}
