//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETFAC
    {
        public string factpro { get; set; }
        public short facitem { get; set; }
        public Nullable<decimal> faccant { get; set; }
        public Nullable<short> FACDESC { get; set; }
        public string FACIMP { get; set; }
        public Nullable<decimal> FACIMPU { get; set; }
        public string facdescri { get; set; }
        public Nullable<decimal> facpreci { get; set; }
    }
}
