//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETMOV
    {
        public string Numero_docu { get; set; }
        public string Eys { get; set; }
        public string Tipodoc { get; set; }
        public short detmoitem { get; set; }
        public string producto { get; set; }
        public string Cod_product { get; set; }
        public string TIPO_BODEGA { get; set; }
        public string Icod_tipo { get; set; }
        public Nullable<decimal> DEQUIVALE { get; set; }
        public Nullable<decimal> DCANTIDAD { get; set; }
        public Nullable<decimal> DPRECIO { get; set; }
        public Nullable<decimal> DMULTIPLI { get; set; }
        public Nullable<decimal> DMANOBRA { get; set; }
        public Nullable<decimal> DETPRECIO { get; set; }
        public Nullable<decimal> DSUBTOTAL { get; set; }
        public Nullable<decimal> costo_u { get; set; }
        public Nullable<decimal> DGASTOSIN { get; set; }
        public string DESCRI2 { get; set; }
        public Nullable<short> DESC2_FAC { get; set; }
        public Nullable<short> DESC3_FAC { get; set; }
        public string marque { get; set; }
        public Nullable<decimal> dtarjet { get; set; }
        public string DLINEA { get; set; }
        public string dnumef { get; set; }
        public string CNUEVOCODI { get; set; }
        public Nullable<decimal> DGSUBTOTAL { get; set; }
        public string para_bodega { get; set; }
        public Nullable<short> lib1 { get; set; }
        public string DETBODEGA { get; set; }
        public string CODIGO_BODE { get; set; }
        public string IDESCRIPCIO { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string CARGAR { get; set; }
        public Nullable<System.DateTime> dfecha { get; set; }
        public Nullable<decimal> Desc_fact { get; set; }
        public Nullable<decimal> Precio_unit { get; set; }
        public Nullable<decimal> IMP { get; set; }
        public Nullable<decimal> SUB_IMP { get; set; }
        public Nullable<decimal> comis_ve { get; set; }
        public Nullable<decimal> sub_libera { get; set; }
        public string DCLIENTE { get; set; }
    }
}
