//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETMTI
    {
        public string mtins_codig { get; set; }
        public string Cod_product { get; set; }
        public string mtins_descr { get; set; }
        public string mtins_unida { get; set; }
        public Nullable<decimal> mtins_canti { get; set; }
        public Nullable<decimal> mtins_preci { get; set; }
    }
}
