//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETMAE
    {
        public string A_codigo { get; set; }
        public string cod_compani { get; set; }
        public string A_cta_conta { get; set; }
        public Nullable<decimal> A_PORCENT { get; set; }
    }
}
