//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETPRO
    {
        public string COD_PROYECT { get; set; }
        public short PRO_ITEM { get; set; }
        public string Cod_product { get; set; }
        public Nullable<short> pro_teclin { get; set; }
        public Nullable<short> pro_tecli2 { get; set; }
        public Nullable<short> pro_tecli3 { get; set; }
        public Nullable<short> P_DESC { get; set; }
        public Nullable<short> P_DESC2 { get; set; }
        public Nullable<short> P_DESC3 { get; set; }
        public string pro_unidad { get; set; }
        public string DESCRI_PROY { get; set; }
        public Nullable<decimal> CANT_PROY { get; set; }
        public Nullable<decimal> PPRECIOPRO { get; set; }
        public Nullable<System.DateTime> fechag_cier { get; set; }
        public Nullable<decimal> PRECIO_PROY { get; set; }
        public string CARGUE_PROY { get; set; }
        public Nullable<decimal> PRO_DTARJET { get; set; }
        public decimal SUB_PROLIB { get; set; }
        public Nullable<decimal> IMP_PROY { get; set; }
    }
}
