//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETSEG
    {
        public string SEG_USUARIO { get; set; }
        public string SEG_ARCHIVO { get; set; }
        public string SEG_INS { get; set; }
        public string SEG_UPD { get; set; }
        public string SEG_DEL { get; set; }
    }
}
