//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXIBOD
    {
        public string Cod_product { get; set; }
        public string CODIGO_BODE { get; set; }
        public string TIPO_BODEGA { get; set; }
        public string Icod_tipo { get; set; }
        public string enuevocodi { get; set; }
        public Nullable<System.DateTime> EXI_DATE { get; set; }
        public Nullable<decimal> EXI_BOD { get; set; }
        public Nullable<decimal> exi_fina { get; set; }
        public Nullable<decimal> reserva { get; set; }
        public Nullable<decimal> exist_cierr { get; set; }
        public Nullable<decimal> exisf_cierr { get; set; }
        public Nullable<System.DateTime> fecha_cierr { get; set; }
        public Nullable<decimal> EXI_CAPTURA { get; set; }
        public Nullable<decimal> EXI_CONGELA { get; set; }
        public Nullable<System.DateTime> EXI_FECHA { get; set; }
        public Nullable<System.DateTime> exi_fecong { get; set; }
        public string exi_horcap { get; set; }
        public string EXI_DIGITO { get; set; }
    }
}
