//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTCLI
    {
        public string HISTC_CODIG { get; set; }
        public System.DateTime HISTC_FECHA { get; set; }
        public string HISTC_HORA { get; set; }
        public string HISTC_TERMI { get; set; }
        public string HISTC_NOMAN { get; set; }
        public string HISTC_NOMAC { get; set; }
    }
}
