//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTP21
    {
        public string cod_listpre { get; set; }
        public string Cod_product { get; set; }
        public string pluref { get; set; }
        public string stockcode { get; set; }
        public Nullable<decimal> lpreciodol { get; set; }
    }
}
