//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAccesoApp
    {
        public int idlinea { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string Ventana { get; set; }
        public string NombreReporte { get; set; }
        public Nullable<System.DateTime> FechaReporteCriterio { get; set; }
        public Nullable<System.DateTime> FechaReporteCriterio2 { get; set; }
        public string HoraActualRun { get; set; }
        public string CriterioGestor { get; set; }
        public string Criterio2 { get; set; }
        public string Criterio3 { get; set; }
    }
}
