//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogContrat1Web
    {
        public int idline { get; set; }
        public string Codigo_clie { get; set; }
        public string cont_numero { get; set; }
        public string JardinAnterior { get; set; }
        public string JardinActual { get; set; }
        public string UbicAnterior { get; set; }
        public string UbicActual { get; set; }
        public Nullable<System.DateTime> fechacambio { get; set; }
        public string hora { get; set; }
        public string usuario { get; set; }
    }
}
