//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATICO
    {
        public string ccod_tipo { get; set; }
        public string cnombre_tip { get; set; }
        public string correl_si_n { get; set; }
        public Nullable<short> correl_pa { get; set; }
    }
}
