//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATIIN
    {
        public string Icod_tipo { get; set; }
        public string Inombre_tip { get; set; }
        public Nullable<decimal> MULTIPLI { get; set; }
        public Nullable<decimal> Iequivale { get; set; }
    }
}
