//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVCXCLE
    {
        public string MOVCX_TIPO { get; set; }
        public string MOVCX_ITEM { get; set; }
        public string Cod_zona { get; set; }
        public string MOVCX_CUENT { get; set; }
        public string MOVCX_DCUEN { get; set; }
        public string MOVCX_2CUEN { get; set; }
        public string MOVCX_2DCUE { get; set; }
    }
}
