//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class OJARDLEV
    {
        public string CONT_NUMERO { get; set; }
        public short OJARD_ITEM { get; set; }
        public string OJARD_CJARD { get; set; }
        public string OJARD_CNUM { get; set; }
        public string OJARD_CLETR { get; set; }
    }
}
