//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGARES
    {
        public string Nump_doc { get; set; }
        public string Tdocp { get; set; }
        public string codprovee { get; set; }
        public string PCONCEPTO { get; set; }
        public string PCONCEP2 { get; set; }
        public Nullable<decimal> PCAMBIO { get; set; }
        public Nullable<System.DateTime> Fechap_reci { get; set; }
        public Nullable<System.DateTime> PFECHA { get; set; }
        public string cxp_partida { get; set; }
        public Nullable<decimal> Porp_lempir { get; set; }
        public string BNumero_cue { get; set; }
        public string CXP_CTIPO { get; set; }
        public string Cod_proveed { get; set; }
        public string pusuario { get; set; }
        public string pterminal { get; set; }
        public string PTERMINO { get; set; }
        public string PLUGAR { get; set; }
        public string PNACIOEXT { get; set; }
        public string PAGARMODIFI { get; set; }
        public Nullable<System.DateTime> PAGARFMODIF { get; set; }
        public string pconciliado { get; set; }
        public string PAGARBORRAD { get; set; }
        public Nullable<System.DateTime> PAGARFBORRA { get; set; }
    }
}
