//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAPEVENL
    {
        public string Cod_vendedo { get; set; }
        public System.DateTime PAPE_FECHA { get; set; }
        public Nullable<int> PAPE_DESDE { get; set; }
        public Nullable<int> PAPE_HASTA { get; set; }
    }
}
