//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMIS
    {
        public string PERM_NUMERO { get; set; }
        public string Cod_product { get; set; }
        public Nullable<System.DateTime> PERM_FECHA { get; set; }
        public string PERM_TIPO { get; set; }
        public Nullable<decimal> PERM_PRECIO { get; set; }
        public Nullable<decimal> PERM_PRENOR { get; set; }
    }
}
