//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACAB
    {
        public string P_num_plani { get; set; }
        public Nullable<System.DateTime> P_f_inicio { get; set; }
        public Nullable<System.DateTime> p_desdefech { get; set; }
        public Nullable<System.DateTime> p_hastafech { get; set; }
        public string P_cod_plani { get; set; }
        public string p_cerrada { get; set; }
        public string pla_partida { get; set; }
        public Nullable<System.DateTime> pla_comdesd { get; set; }
        public Nullable<System.DateTime> pla_comhast { get; set; }
        public string P_MODIFICAD { get; set; }
        public string p_pagsegu { get; set; }
        public string p_placomis { get; set; }
        public string p_pselplan { get; set; }
    }
}
