//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACAL
    {
        public string P_num_plani { get; set; }
        public int P_num_emple { get; set; }
        public System.DateTime P_fecha { get; set; }
        public string p_nombdia { get; set; }
        public Nullable<decimal> P_hora_entr { get; set; }
        public Nullable<decimal> p_hora2_sal { get; set; }
        public Nullable<decimal> p_hora2_ent { get; set; }
        public Nullable<decimal> P_hora_sali { get; set; }
        public Nullable<decimal> P_horas_int { get; set; }
        public string p_cubierta { get; set; }
        public string p_cubnomb { get; set; }
    }
}
