//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACON
    {
        public string P_control { get; set; }
        public string P_empresa { get; set; }
        public Nullable<decimal> P_fosovi { get; set; }
        public string P_numero_pa { get; set; }
        public string P_razon_soc { get; set; }
        public string P_tipo_empr { get; set; }
        public string P_sector { get; set; }
        public string P_actividad { get; set; }
        public string P_direccion { get; set; }
        public string P_telefono { get; set; }
        public string P_fax { get; set; }
        public Nullable<decimal> P_numero_fo { get; set; }
        public Nullable<decimal> P_DEPRECIA { get; set; }
    }
}
