//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLADHI
    {
        public string ph_numpla { get; set; }
        public int ph_numemp { get; set; }
        public string ph_coddep { get; set; }
        public string ph_nomdep { get; set; }
        public string ph_nomemp { get; set; }
        public string ph_nompuest { get; set; }
        public Nullable<decimal> ph_diastrab { get; set; }
        public Nullable<decimal> ph_sueldia { get; set; }
        public Nullable<decimal> ph_septimo { get; set; }
        public Nullable<decimal> ph_extnum { get; set; }
        public Nullable<decimal> ph_dobnum { get; set; }
        public Nullable<decimal> ph_sueldo { get; set; }
        public Nullable<decimal> PH_ANTICIPO { get; set; }
        public Nullable<decimal> PH_VENTAS { get; set; }
        public Nullable<decimal> PH_HORASE { get; set; }
        public Nullable<decimal> ph_25 { get; set; }
        public Nullable<decimal> ph_50 { get; set; }
        public Nullable<decimal> ph_75 { get; set; }
        public Nullable<decimal> ph_100 { get; set; }
        public Nullable<decimal> ph_extras { get; set; }
        public Nullable<decimal> ph_otrosing { get; set; }
        public Nullable<decimal> ph_devengad { get; set; }
        public Nullable<decimal> ph_isr { get; set; }
        public Nullable<decimal> PH_AJUSTE { get; set; }
        public Nullable<decimal> ph_cuentcob { get; set; }
        public Nullable<decimal> ph_municipa { get; set; }
        public Nullable<decimal> ph_transpor { get; set; }
        public Nullable<decimal> ph_prestamo { get; set; }
        public Nullable<decimal> ph_ihss { get; set; }
        public Nullable<decimal> ph_fosovi { get; set; }
        public Nullable<decimal> ph_otrasded { get; set; }
        public Nullable<decimal> ph_deducido { get; set; }
        public Nullable<decimal> ph_total { get; set; }
        public Nullable<decimal> ph_valcamb { get; set; }
        public Nullable<decimal> ph_bonoasi { get; set; }
        public Nullable<decimal> ph_incapa { get; set; }
        public Nullable<int> PH_REFERE { get; set; }
        public Nullable<decimal> PH_BONOSUP { get; set; }
        public string PH_VDIREC { get; set; }
        public string PH_BANCO { get; set; }
        public string ph_devac { get; set; }
        public Nullable<System.DateTime> PH_DFECHA { get; set; }
        public Nullable<decimal> ph_sueldoba { get; set; }
        public Nullable<decimal> ph_comision { get; set; }
        public Nullable<decimal> ph_cooperat { get; set; }
        public Nullable<decimal> ph_compa1 { get; set; }
        public Nullable<decimal> ph_compa2 { get; set; }
        public Nullable<decimal> ph_compa3 { get; set; }
        public Nullable<decimal> ph_compa4 { get; set; }
        public Nullable<decimal> PH_VACACI { get; set; }
        public string ph_sucur { get; set; }
        public string ph_tranck { get; set; }
    }
}
