//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLADET
    {
        public string P_num_plani { get; set; }
        public int P_num_emple { get; set; }
        public Nullable<decimal> P_COMISON { get; set; }
        public Nullable<decimal> P_Cuentcob { get; set; }
        public Nullable<decimal> P_PRESTAMOS { get; set; }
        public Nullable<decimal> P_ANTICIPO { get; set; }
        public string p_fijacob { get; set; }
        public string p_deduauto { get; set; }
        public Nullable<decimal> P_RETMUNIC { get; set; }
        public Nullable<decimal> P_TRANSPORT { get; set; }
        public Nullable<decimal> P_ext25 { get; set; }
        public Nullable<decimal> P_ext50 { get; set; }
        public Nullable<decimal> P_ext75 { get; set; }
        public Nullable<decimal> P_ext100 { get; set; }
        public Nullable<decimal> p_sumardias { get; set; }
        public Nullable<decimal> P_ausencia { get; set; }
        public Nullable<short> p_sumediasc { get; set; }
        public Nullable<decimal> P_PLAISR { get; set; }
        public Nullable<decimal> P_AJUSTE { get; set; }
        public string P_OBSERV { get; set; }
        public Nullable<decimal> p_ajustemin { get; set; }
        public Nullable<decimal> P_ventasm01 { get; set; }
        public Nullable<decimal> p_ventasm02 { get; set; }
        public Nullable<decimal> p_ventasm03 { get; set; }
        public Nullable<decimal> p_ventasm04 { get; set; }
        public Nullable<decimal> p_ventasp01 { get; set; }
        public Nullable<decimal> p_premiom01 { get; set; }
        public Nullable<decimal> p_premiom02 { get; set; }
        public Nullable<decimal> p_premiom03 { get; set; }
        public Nullable<decimal> p_premiom04 { get; set; }
        public Nullable<decimal> p_premiop01 { get; set; }
        public Nullable<decimal> p_reacanm01 { get; set; }
        public Nullable<decimal> p_reacanm02 { get; set; }
        public Nullable<decimal> p_reacanm03 { get; set; }
        public Nullable<decimal> p_reacanm04 { get; set; }
        public Nullable<decimal> p_reacanp01 { get; set; }
        public Nullable<decimal> P_SUBINGRE { get; set; }
        public Nullable<decimal> p_cxcm01 { get; set; }
        public Nullable<decimal> p_cxcm02 { get; set; }
        public Nullable<decimal> p_cxcm03 { get; set; }
        public Nullable<decimal> p_cxcm04 { get; set; }
        public Nullable<decimal> p_cxcp01 { get; set; }
        public Nullable<decimal> P_SUBEGRE { get; set; }
        public Nullable<short> P_SUPJAR { get; set; }
        public Nullable<short> P_SUPMEM { get; set; }
        public Nullable<decimal> P_VENTJAR { get; set; }
        public Nullable<decimal> P_VENTMEM { get; set; }
        public Nullable<decimal> P_MVALCOBR { get; set; }
        public Nullable<decimal> P_JVALCOBR { get; set; }
        public Nullable<decimal> P_SALDOANT { get; set; }
        public string P_ULTIMEM { get; set; }
        public string P_ULTIJAR { get; set; }
        public string P_CUEBAN { get; set; }
        public string P_NUMCHEQ { get; set; }
        public Nullable<decimal> P_letramoto { get; set; }
        public string p_numletmo { get; set; }
        public Nullable<decimal> p_combustib { get; set; }
        public Nullable<System.DateTime> p_fechapago { get; set; }
        public string p_compa { get; set; }
        public string P_SUCU { get; set; }
        public string p_pagdepre { get; set; }
        public Nullable<decimal> P_DIHSS { get; set; }
        public Nullable<decimal> p_dvalcomb { get; set; }
    }
}
