//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLADEP
    {
        public string P_cod_depar { get; set; }
        public string P_nomb_depa { get; set; }
        public string p_ctagasfos { get; set; }
        public string p_ctadeprec { get; set; }
        public string p_ctagasihs { get; set; }
        public string p_ctagastin { get; set; }
        public string p_ctagpasiv { get; set; }
    }
}
