//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLADMA
    {
        public int P_num_emple { get; set; }
        public string PM_DEPTO { get; set; }
        public string PM_NOMDEP { get; set; }
        public Nullable<decimal> PM_PORCENT { get; set; }
        public Nullable<decimal> PM_VALOR { get; set; }
    }
}
