//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAINCA
    {
        public int P_n_incapac { get; set; }
        public Nullable<int> P_num_emple { get; set; }
        public Nullable<System.DateTime> P_f_incapac { get; set; }
        public string P_t_incapac { get; set; }
        public Nullable<short> P_d_incapac { get; set; }
        public string P_incobs1 { get; set; }
        public string P_incobs2 { get; set; }
    }
}
