//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAVAC
    {
        public int P_n_vacacio { get; set; }
        public Nullable<int> P_num_emple { get; set; }
        public Nullable<System.DateTime> P_f_vacacio { get; set; }
        public Nullable<decimal> P_d_vacacio { get; set; }
        public Nullable<short> P_d_fevaca { get; set; }
        public string P_t_vacacio { get; set; }
        public Nullable<decimal> P_a_vacacio { get; set; }
        public Nullable<decimal> P_aa_vacaci { get; set; }
        public Nullable<System.DateTime> p_f_vacregr { get; set; }
        public string P_VACONCEP { get; set; }
        public string p_vaconc2 { get; set; }
        public string P_VACPLANI { get; set; }
    }
}
