//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLDOCDED
    {
        public string PLD_NUMERO { get; set; }
        public Nullable<System.DateTime> PLD_FECHA { get; set; }
        public Nullable<int> P_num_emple { get; set; }
        public Nullable<decimal> PLD_VALOR { get; set; }
        public Nullable<decimal> PLD_DEDUCIR { get; set; }
        public string PLD_PARTIDA { get; set; }
        public string PLD_CONCEPT { get; set; }
        public string PLD_CODCONC { get; set; }
        public string PLD_CONC2 { get; set; }
    }
}
