//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLOPAUTL
    {
        public int P_num_emple { get; set; }
        public short PLOPA_ITEM { get; set; }
        public string PLOP_CODIGO { get; set; }
        public string PLOP_NOMBRE { get; set; }
        public string PLOP_TIPO { get; set; }
        public Nullable<decimal> PLOP_VALOR { get; set; }
    }
}
