//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPOPER
    {
        public string P_num_plani { get; set; }
        public int P_num_emple { get; set; }
        public string P_cod_opera { get; set; }
        public Nullable<decimal> P_VAL_OPERA { get; set; }
    }
}
