//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMO
    {
        public string PREST_NUMER { get; set; }
        public string PREST_TIPO { get; set; }
        public string PREST_BANCO { get; set; }
        public string PREST_BDESC { get; set; }
        public string PREST_CUENT { get; set; }
        public string PREST_CUINT { get; set; }
        public string PREST_GAR1 { get; set; }
        public string PREST_GAR2 { get; set; }
        public Nullable<System.DateTime> PREST_VENCE { get; set; }
        public string PREST_MONED { get; set; }
        public string PREST_FACTU { get; set; }
        public Nullable<System.DateTime> prest_fechi { get; set; }
        public Nullable<decimal> PREST_SALDO { get; set; }
        public Nullable<decimal> PREST_CAMBI { get; set; }
        public Nullable<decimal> PREST_INTER { get; set; }
        public string PREST_COMPA { get; set; }
    }
}
