//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public string Cod_product { get; set; }
        public string Descripcion { get; set; }
        public string SINCOMISION { get; set; }
        public string Codigo_area { get; set; }
        public string cod_subgru { get; set; }
        public string pnomsubgru { get; set; }
        public string REFERENCIA { get; set; }
        public string cod_barra { get; set; }
        public string especifi { get; set; }
        public string UNI_PRESEN { get; set; }
        public string PROD_IMP { get; set; }
        public Nullable<decimal> prod_impues { get; set; }
        public string pprovee { get; set; }
        public Nullable<decimal> Precio_deta { get; set; }
        public Nullable<decimal> PrecioA { get; set; }
        public string Costo_clave { get; set; }
        public Nullable<decimal> Costo_unita { get; set; }
        public Nullable<decimal> FCOSTO_UNIT { get; set; }
        public Nullable<int> Punto_minim { get; set; }
        public Nullable<int> Punto_reord { get; set; }
        public Nullable<int> Punto_maxim { get; set; }
        public Nullable<decimal> Existencia { get; set; }
        public string PROD_STATUS { get; set; }
        public Nullable<decimal> FEXISTENCIA { get; set; }
        public Nullable<decimal> Aumento { get; set; }
        public Nullable<decimal> Exifis { get; set; }
        public Nullable<decimal> Exifis2 { get; set; }
        public Nullable<decimal> EXISUC { get; set; }
        public Nullable<decimal> BOD1 { get; set; }
        public Nullable<decimal> BOD2 { get; set; }
        public string bodenf1 { get; set; }
        public string bodenf2 { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> DOLARCOSTO { get; set; }
        public Nullable<decimal> ucosto { get; set; }
        public string OPERAR { get; set; }
        public Nullable<short> PRODESC1 { get; set; }
        public Nullable<short> PRODESC2 { get; set; }
        public Nullable<short> PRODESC3 { get; set; }
        public string BODENT { get; set; }
        public string pcatalo { get; set; }
        public string prod_usuari { get; set; }
        public string prod_termin { get; set; }
        public Nullable<decimal> exisgf_cier { get; set; }
        public Nullable<decimal> existg_cier { get; set; }
        public Nullable<decimal> costog_cier { get; set; }
        public Nullable<decimal> costgf_cier { get; set; }
        public Nullable<decimal> precioC { get; set; }
        public Nullable<decimal> precio_back { get; set; }
        public Nullable<decimal> precioD { get; set; }
        public Nullable<System.DateTime> prod_f_cal { get; set; }
        public string prod_n_cal { get; set; }
        public string nuevocodi { get; set; }
        public Nullable<decimal> BOD3 { get; set; }
        public string CAPTURO3 { get; set; }
        public Nullable<decimal> EXIFIS3 { get; set; }
        public string BODENF3 { get; set; }
        public string PROD_PROVE { get; set; }
        public Nullable<System.DateTime> PROD_FECHU { get; set; }
        public Nullable<decimal> costo_INICI { get; set; }
        public string produb_codi { get; set; }
        public Nullable<decimal> precioB { get; set; }
        public string PROD_PARTAR { get; set; }
        public Nullable<decimal> costo_desar { get; set; }
        public string PROD_UBICAC { get; set; }
        public Nullable<decimal> PROD_INCA { get; set; }
        public Nullable<decimal> PROD_INCB { get; set; }
        public Nullable<decimal> PROD_INCC { get; set; }
        public Nullable<decimal> utilidad { get; set; }
        public Nullable<decimal> Precio_mayo { get; set; }
    }
}
