//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROEXI
    {
        public string codi_pro { get; set; }
        public string Cod_product { get; set; }
        public string PRODESCRI { get; set; }
        public Nullable<decimal> proexi1 { get; set; }
        public Nullable<short> propdesc1 { get; set; }
        public Nullable<short> propdesc2 { get; set; }
        public Nullable<short> propdesc3 { get; set; }
        public Nullable<decimal> PROPRECIO { get; set; }
    }
}
