//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICI1
    {
        public string serv_tipo { get; set; }
        public string serv_codigo { get; set; }
        public short serv_item { get; set; }
        public Nullable<System.DateTime> serv_desdef { get; set; }
        public Nullable<System.DateTime> serv_hastaf { get; set; }
        public Nullable<decimal> serv_comis { get; set; }
        public Nullable<decimal> serv_2com { get; set; }
        public Nullable<decimal> serv_3com { get; set; }
        public Nullable<decimal> serv_sala { get; set; }
    }
}
