//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        public string Codigo_sucu { get; set; }
        public string Nombre_sucu { get; set; }
        public string cod_compani { get; set; }
        public string Dir_sucursa { get; set; }
        public string Ciudad_sucu { get; set; }
        public string Telef_sucur { get; set; }
        public string Apart_sucur { get; set; }
        public string E_C_COBRAR { get; set; }
        public string E_V_CREDITO { get; set; }
        public string E_V_CONTADO { get; set; }
        public string E_I_S_VENTA { get; set; }
        public string E_C_GENERAL { get; set; }
        public string E_D_DIVERSO { get; set; }
        public string E_C_EMPLEAD { get; set; }
        public string E_COMPRAS { get; set; }
        public string E_I_S_COMPR { get; set; }
        public string E_C_PAGAR { get; set; }
        public string E_C_DOCUMEN { get; set; }
        public string E_C_PRESTAM { get; set; }
        public string E_C_BANCOS { get; set; }
        public string E_C_INTPRES { get; set; }
        public string EA_FINANCI { get; set; }
        public string EA_FLETES { get; set; }
        public Nullable<int> CORF_CAJA1 { get; set; }
        public Nullable<int> CORF_CAJA2 { get; set; }
        public Nullable<int> CORF_CAJA3 { get; set; }
        public string E_V_CONT2 { get; set; }
        public string EA_INVENTA { get; set; }
        public Nullable<decimal> requita { get; set; }
        public string SUC_LETRA { get; set; }
        public Nullable<decimal> requient { get; set; }
        public Nullable<decimal> ORDARMADO { get; set; }
        public Nullable<decimal> trasla { get; set; }
        public string sysbodega { get; set; }
        public string dir2_sucurs { get; set; }
        public string suc_rtn { get; set; }
        public string SUC_IMPC1 { get; set; }
        public string SUC_IMPC2 { get; set; }
        public Nullable<decimal> suc_totalco { get; set; }
    }
}
