//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECNICOS
    {
        public int cod_tecnico { get; set; }
        public string nombre_tecn { get; set; }
        public string TIPO_TECNIC { get; set; }
        public string empresa { get; set; }
        public string rtn { get; set; }
        public string tec_depto { get; set; }
        public string tec_jefeinm { get; set; }
        public string tec_jeferec { get; set; }
        public string tec_telefon { get; set; }
        public string tidentidad { get; set; }
        public string tec_status { get; set; }
        public string tec_usuario { get; set; }
        public string tec_inactiv { get; set; }
        public string tec_modific { get; set; }
        public System.DateTime tec_fecmodi { get; set; }
        public short TEC_TOPELI { get; set; }
        public string tec_domicil { get; set; }
        public string tec_celular { get; set; }
        public string tec_telcasa { get; set; }
        public string tec_dirnego { get; set; }
        public string tec_cliepri { get; set; }
        public string tec_2cliepr { get; set; }
        public string tec_3cliepr { get; set; }
        public string TEC_SUCURSA { get; set; }
        public string TEC_PASAPOR { get; set; }
    }
}
