//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALES
    {
        public string VAL_EMPRESA { get; set; }
        public int VAL_NUMERO { get; set; }
        public Nullable<System.DateTime> VAL_FECHA { get; set; }
        public Nullable<decimal> VAL_VALOR { get; set; }
        public string codigo_cobr { get; set; }
        public string VAL_CONCEPT { get; set; }
        public string VAL_CONCE2 { get; set; }
        public string VAL_USUARIO { get; set; }
        public string VAL_ANULO { get; set; }
        public string VAL_SUCURS { get; set; }
        public string VAL_NOMBRE { get; set; }
        public string VAL_COMPA { get; set; }
        public Nullable<short> VAL_TIPO { get; set; }
        public string VAL_ANUHORA { get; set; }
        public string VAL_ANUTERM { get; set; }
        public Nullable<System.DateTime> VAL_ANUFECH { get; set; }
    }
}
