//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR
    {
        public string Cod_vendedo { get; set; }
        public string Nombre_vend { get; set; }
        public string Dir_vendedo { get; set; }
        public string Tel_vendedo { get; set; }
        public Nullable<decimal> Comision_ve { get; set; }
        public Nullable<decimal> COMICOB { get; set; }
        public string passvend { get; set; }
        public Nullable<decimal> meta_vended { get; set; }
        public string VEND_STATUS { get; set; }
        public string vend_numbee { get; set; }
        public string vend_telbee { get; set; }
        public string VEND_TIPO { get; set; }
        public string vend_sucu { get; set; }
        public string VEND_LIDER { get; set; }
        public string vzon_codigo { get; set; }
        public Nullable<System.DateTime> VEND_INGRES { get; set; }
        public Nullable<System.DateTime> vend_fechin { get; set; }
        public Nullable<decimal> VEND_VIATIC { get; set; }
        public string vend_teltra { get; set; }
        public string VEND_IDENTI { get; set; }
        public Nullable<System.DateTime> VEND_FECNAC { get; set; }
        public byte[] VEND_FOTO { get; set; }
        public string vend_suplid { get; set; }
    }
}
