//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSistema.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class VZONA
    {
        public string vzon_codigo { get; set; }
        public string vzon_nombre { get; set; }
        public string vzon_ciudad { get; set; }
        public string vzon_empres { get; set; }
        public string vzon_app { get; set; }
    }
}
